### PR TITLE
Server642 is back

### PR DESCRIPTION
**Pull request by FrozenPvPs**
Server642 is back
https://fro.wtf/w9en.png

### CODE REVIEW

**Comment by Qubopp** [comment]
And here we have PR #100!

**Comment by FragbyteHostingLTD** [comment]
Some more evidence...

Another Scam

**Comment by FrozenPvPs** [comment]
> Some more evidence...
> 
> Another Scam

Who is that?
He's not in the Server642 Discord.

**Comment by FragbyteHostingLTD** [comment]
He is part of this discord:
image
Which is the Server642 discord (Well, werid one to say the least, no channels)
image

**Comment by FragbyteHostingLTD** [comment]
He is part of this discord:
image
Which is this discord of Server642. (No channels, very sketchy)
68628675-37df0b00-04d9-11ea-991d-b9737bbb25ca

**Pull request merged**
