### PR TITLE
Added The Protel Group

### PR DESCRIPTION
**Pull request by AnushK-Fro**
SummerHoax

### CODE REVIEW

**Comment by Daxorinator** [comment]
Voting to merge, 100% a summerhoax, used nulled WHMCS and denied it.

**Comment by ZeProf2Code** [comment]
image
image
image

**Comment by KidsAreSalty** [comment]
Dont really see what those screenshots prove

**Comment by ZeProf2Code** [comment]
> Dont really see what those screenshots prove

It's not proving anything, it's just to see the answers of the staff ;)

**Comment by Qubopp** [comment]
Alright- so. We were not using Nulled WHMCS, we bought a license from what we thought was a WHMCS partner, which we later found out sold us a nulled key instead. We weren't using a nulled _copy_ more so a key, which doesn't jeopardize our security. 

Secondly, we're not a summerhoax, we have been in business for 2+ years, have more than 170 happy clients and currently undergoing a branding refresh. 

Pretty much everyone in the SummerHoax community is a SummerHoax themselves so I don't know what you're talking about. 

If you would like to discuss this further, please email me at _christian.c@theprotelgroup.us_ or PM me on Discord at _Gherkin#7748_.

Thanks,
Christian.
**CTO of The Protel Group**

**Comment by Daxorinator** [comment]
"Pretty much everyone in the summerhoax community is a summerhoax themselves"

You know, when your signing off on something as the CTO of the company, you should probably think more carefully about what your writing. Else you might look a bit foolish..

**Comment by hb4uhomebrew** [comment]
> Alright- so. We were not using Nulled WHMCS, we bought a license from what we thought was a WHMCS partner, which we later found out sold us a nulled key instead. We weren't using a nulled _copy_ more so a key, which doesn't jeopardize our security.
> 
> Secondly, we're not a summerhoax, we have been in business for 2+ years, have more than 170 happy clients and currently undergoing a branding refresh.
> 
> Pretty much everyone in the SummerHoax community is a SummerHoax themselves so I don't know what you're talking about.
> 
> If you would like to discuss this further, please email me at _[christian.c@theprotelgroup.us](mailto:christian.c@theprotelgroup.us)_ or PM me on Discord at _Gherkin#7748_.
> 
> Thanks,
> Christian.
> **CTO of The Protel Group**

Should've bought directly from WHMCS, Go away Summerhoax. BEGONE.

**Comment by Daxorinator** [comment]
People like the above are the reason Christian feels the community is mostly summerhoaxes in and of itself. Can't say I disagree with him, but making such an assumption is definitely not a good PR move...

**Comment by Benroyz** [comment]
> Alright- so. We were not using Nulled WHMCS, we bought a license from what we thought was a WHMCS partner, which we later found out sold us a nulled key instead. 
And that is sort of the reason why you should purchase licenses directly instead of "resellers".

**Comment by hb4uhomebrew** [comment]
> People like the above are the reason Christian feels the community is mostly summerhoaxes in and of itself. Can't say I disagree with him, but making such an assumption is definitely not a good PR move...
He probably bought from a shady reseller, If he had funding (170 clients??) Why didn't he just buy directly from WHMCS. Seems shady. no?

**Comment by Qubopp** [comment]
It wasn't an assumption, it is the truth, I am definately not saying **everyone** is a SummerHoax, as there is some notable companies that are fully trustworthy. The reseller we bought from- which I wont name was a company in business for 5+ years and we believed we could trust them. We have since taken action against the reseller and they have changed their ways.

Regards,
Christian C

**Comment by Qubopp** [comment]
And the way the re-seller was modifying the key was strange, as we downloaded standard WHMCS 7.* from the official website and inputted the key like normal, and it displayed like a normal re-seller but it was not appearing on the authorized users page, originally we thought it was a mix up where 2 people got the same key and the other person got the authorization, but we don't know, it was months ago, completely irrelevant.

**Comment by Daxorinator** [comment]
> Pretty much everyone in the SummerHoax community is a SummerHoax themselves so I don't know what you're talking about.

I mean that's fairly encompassing statement.

**Comment by Qubopp** [comment]
Annotation 2019-10-13 042115
Annotation 2019-10-13 042138
Annotation 2019-10-13 042146
Annotation 2019-10-13 042218
Annotation 2019-10-13 042229
Annotation 2019-10-13 042238
Annotation 2019-10-13 042248
Annotation 2019-10-13 042300
Annotation 2019-10-13 042309
Annotation 2019-10-13 042319
Annotation 2019-10-13 042335

**Comment by Qubopp** [comment]
https://fro.wtf/9nwm.gif

**Comment by FrozenPvPs** [comment]
> https://fro.wtf/9nwm.gif

Hey!
Thanks for posting this for me!

So,
Let's review:
You threatened to have a lawsuit against me.
You threatened to "submit an injuction to force you to take it down"
"I will proceed with contacting the Better Business Bureau"
"And my next step is to contact New Jersey stat division of Revenue and Enterprise services"

Fro
Today at 1:50 PM
So now you're threatening to take down my business?
It's literally freedom of speech mate.
There's nothing wrong in expressing my opinion.
 
Gherkin
Today at 1:50 PM
Not take it down- just stating what we will do.
And it's not an opinion.

Fro
Today at 1:50 PM
It's an obvious threat.
 
Gherkin
Today at 1:50 PM
It isn't a threat. It is what we will do.

I saw that you threatened to have a lawsuit, and then you immediately deleted the message after. Let's see how that plays out buddy!

**Comment by Qubopp** [comment]
Plus- that wasn't me that sent the 'threats'.
We haven't threatened a Lawsuit against you.

**Comment by FrozenPvPs** [comment]
> Plus- that wasn't me that sent the 'threats'.
> We haven't threatened a Lawsuit against you.

Well, the other person in the group chat threatened a lawsuit. He deleted the message immediately after.

Also, another thing, if it were true that I could go to court with someone who left a bad review, then I would most likely have 0 bad reviews on my business's Trustpilot.

**Comment by hb4uhomebrew** [comment]
This is all very... very childish. I'm not saying this "ProtelGroup" has anything to hide, but if you are threatening law suits or whatever or trying to threaten his business over.... a meme site... That's childish. If you in theory sue FroHost, LLC defamation of character you will 100% lose. They won't take some random website as proof. Please, Ethereal I ask just to close the PR and just move on. This is childish as hell.

**Comment by Qubopp** [comment]
Well- he didn't threaten a Lawsuit, he threatened an injunction- which is completely different.
And _if_ we took you to court, it wouldn't be for writing bad reviews it would be the backlash that it caused.

**Comment by FrozenPvPs** [comment]
> Well- he didn't threaten a Lawsuit, he threatened an injunction- which is completely different.
> And _if_ we took you to court, it wouldn't be for writing bad reviews it would be the backlash that it caused.

That's where you're wrong.
Yes, he did.
I saw it with my own eyes and then he deleted the message right after.

**Comment by Qubopp** [comment]
Ok- show me proof.
I could say I saw my dead nan with my eyes last night, is there proof, no, there isn't.

**Comment by KidsAreSalty** [comment]
These guys are a total meme lol add them to the list and hang em in the process

**Comment by FrozenPvPs** [comment]
> Ok- show me proof.
> I could say I saw my dead nan with my eyes last night, is there proof, no, there isn't.

Did I not say he immediately deleted it right after?

**Comment by Qubopp** [comment]
Did I not say I saw my dead nan?

**Comment by Daxorinator** [comment]
I don't know what you think your filing an injunction for.

What are you going to do, sue for defamation?

**Comment by Qubopp** [comment]
@FrozenPvPs Just close the damn PR this is getting ridiculous

**Comment by hb4uhomebrew** [comment]
https://i.imgur.com/xdzowQ7.png So, this is a thing. They claim many customers are complaining about the Pull Request of the joke site, Summerhoax.com which had never gone through the system fully. Yet... Only 1 message in there discord containing summerhoax. Claiming it was a lot in there live chat
image

Fro, Close this. This is absolutely stupid. In my opinion let's keep an eye on them but this has gotten out of control.

**Comment by Daxorinator** [comment]
What's ridiculous is you guys threatening to file an injunction, and what seems to be a threat to sue for defamation with absolutely 0 cause. If this is pissing you off so much, why don't you just defend yourself then not reply again on the PR? Surely you understand that's the best course of action besides taking up an offense against what you call "the summerhoaxes running summerhoax"

**Comment by Qubopp** [comment]
Not replying would be WORSE than defending.

**Comment by Daxorinator** [comment]
There is no reason to close this pull request, and this pull request shouldn't be closed. If it is to be closed, it will be closed by one of the administrators. Under the circumstances I think more investigation is needed, because at first this seemed plausible, then it seemed like a case of mis-information, now we've gone full circle and we're looking at a possible summerhoax again.

**Comment by hb4uhomebrew** [comment]
Wow ok, so one of the owners was just harassing me in the group chat and then kicked me, yeah I'm not so sure about this host..

**Comment by Qubopp** [comment]
Harassing you in the group chat? Evidence please.

**Comment by FrozenPvPs** [comment]
> Did I not say I saw my dead nan?

Honestly, I'm done with you. I'm not going to waste any more time.
Ask the other guy in the group, he said it and immediately deleted it.
I don't know what you want me to say.

You're being really childish and this is just a total meme.
If you want to email the documents, go ahead. My email is fro@fro.email
You'll just waste a bunch of time and money, you will lose.

I just own a small hosting company. That's all. 

Here's the full chat log for those of you who want to read it:
https://ptero.co/ipamuvejop.sql

This is a gif of the group chat I was added in:
https://fro.wtf/9nwm.gif

> https://i.imgur.com/xdzowQ7.png So, this is a thing. They claim many customers are complaining about the Pull Request of the joke site, Summerhoax.com which had never gone through the system fully. Yet... Only 1 message in there discord containing summerhoax. Claiming it was a lot in there live chat
> image
> 
> Fro, Close this. This is absolutely stupid. In my opinion let's keep an eye on them but this has gotten out of control.

I will not be closing this.
Eth can review all of the evidence and PR it. 
It's completely obvious that they are a SummerHoax.

**Comment by hb4uhomebrew** [comment]
> Harassing you in the group chat? Evidence please.

*sighs* Did you even read what I said? I got kicked. I don't want to be in contact with any of the team @ The Protel Group any further. Goodbye.

**Comment by hb4uhomebrew** [comment]
It was Christian, CTO of Protel Group.

**Comment by Qubopp** [comment]
Ok? You posted my name, complete public knowledge, heck, you scratch slightly beneath the surface you'll find my school, slightly more, my address.

**Comment by hb4uhomebrew** [comment]
> Ok? You posted my name, complete public knowledge, heck, you scratch slightly beneath the surface you'll find my school, slightly more, my address.

Why would I want any of that..? I have no interest in contacting you.

**Comment by Qubopp** [comment]
I don't know I'm just saying, you just posted my name.

**Comment by hb4uhomebrew** [comment]
> I don't know I'm just saying, you just posted my name.

Only reason I know your name is because you have yourself nick named on "The Protel Group" Discord.

**Comment by hb4uhomebrew** [comment]
If you want me to not quote your name, I will delete that comment and re-comment it without your name referring to you as CTO.

**Comment by Qubopp** [comment]
I don't care that you posted it, I was just confused _ why_ you posted it :/

**Comment by hb4uhomebrew** [comment]
> I don't care that you posted it, I was just confused _ why_ you posted it :/

For record when you sue FroHost

**Comment by hb4uhomebrew** [comment]
Why so respectful in the PR but not in dm's or the group chat, hiding somethin?

**Comment by Qubopp** [comment]
Lmao what?

**Comment by hb4uhomebrew** [comment]
> Lmao what?

*Quick Quick start acting normal* Whatever I posted proof on revenact peace man.

**Comment by ZeProf2Code** [comment]
image
wait what

**Comment by Daxorinator** [comment]
ANNNND that's a merge.

**Comment by KidsAreSalty** [comment]
Idk who sent that but please send one to my email to: zbro4046@gmail.com I love dealing with petty kids like this :D who remembers that Savage guy from FlashNode? He said the same thing and I even gave him my address in order to make it easier for him... still waiting for the summons 6 months later

**Comment by FrozenPvPs** [comment]
> image
> wait what

I died reading that. 
They basically told me to remove the PR otherwise they would take legal action too (except on Discord) lool.

**Comment by Ethereal739** [comment]
> Alright- so. We were not using Nulled WHMCS, we bought a license from what we thought was a WHMCS partner, which we later found out sold us a nulled key instead. We weren't using a nulled _copy_ more so a key, which doesn't jeopardize our security.
> 
> Secondly, we're not a summerhoax, we have been in business for 2+ years, have more than 170 happy clients and currently undergoing a branding refresh.
> 
> Pretty much everyone in the SummerHoax community is a SummerHoax themselves so I don't know what you're talking about.
> 
> If you would like to discuss this further, please email me at _[christian.c@theprotelgroup.us](mailto:christian.c@theprotelgroup.us)_ or PM me on Discord at _Gherkin#7748_.
> 
> Thanks,
> Christian.
> **CTO of The Protel Group**

A feel question:

Do you guys own https://neesp.fr/ and https://purecpu.com/?

**Comment by Qubopp** [comment]
No mate, we dont @Ethereal739

**Comment by Ethereal739** [comment]
Are you going to take legal action against these guys then?
https://neesp.fr/
image

**Comment by Qubopp** [comment]
Am I missing something?

**Comment by Ethereal739** [comment]
My bad, the guy changed the registration on his website already

**Comment by Ethereal739** [comment]
What is your company registration number?

**Comment by Ethereal739** [comment]
@Qubopp Also, a quick whois lookup shows that your domain has only been registered for just over a year

image

**Comment by Qubopp** [comment]
We have multiple domains in use.

**Comment by Ethereal739** [comment]
> We have multiple domains in use.

Such as?
And what is the company registration number?

**Comment by DamonOnYT** [comment]
https://theprotelgroup.us/cart.php?gid=23

They are clearly illegally selling Teamspeak servers, as the pricing does not make sense 

Though 32 slot TeamSpeak servers are free for personal use, They are not cheap when coming to selling when authorised.

**Comment by Qubopp** [comment]
Our reseller is authorised to sell TeamSpeak servers.

**Comment by FrozenPvPs** [comment]
> Our reseller is authorised to sell TeamSpeak servers.

Hey buddy!
What is the company registration number and what are your other domains?
Answer the question, stop avoiding it.

**Comment by Endeavor756** [comment]
> Alright- so. We were not using Nulled WHMCS, we bought a license from what we thought was a WHMCS partner, which we later found out sold us a nulled key instead. We weren't using a nulled _copy_ more so a key, which doesn't jeopardize our security.
> 
> Secondly, we're not a summerhoax, we have been in business for 2+ years, have more than 170 happy clients and currently undergoing a branding refresh.
> 
> Pretty much everyone in the SummerHoax community is a SummerHoax themselves so I don't know what you're talking about.
> 
> If you would like to discuss this further, please email me at _[christian.c@theprotelgroup.us](mailto:christian.c@theprotelgroup.us)_ or PM me on Discord at _Gherkin#7748_.
> 
> Thanks,
> Christian.
> **CTO of The Protel Group**

So this is from the start of the PR, but I like how you say

> We weren't using a nulled _copy_ more so a key, which doesn't jeopardize our security.

Which is completely wrong by the way. Keys can't be nulled. They can be purchased or leaked. Leaked keys are still retail keys that have gone public due to carelessness of the client OR due to malice committed by someone, thus stealing the key from their account. That means you can use a stolen key with a retail copy, since it still is a stolen key, but nonetheless a retail one.

Which brings me to my next point; WHMCS has IP licensing. If the key truly was "nulled" (stolen), it wouldn't work anyway since it stores the IP of the first machine that used it and I doubt that was you if it was truly stolen, since it probably has been used by its legitimate owner before.

**Comment by Qubopp** [comment]
Then it must of been stolen or leaked, either way, our Reseller was doing something dodgy with the licensing, we used an official version from the WHMCS website. If you would like to know our other domains, you can Private Message me on Discord, as we don't want to disclose them publically.

Thanks,
Christian Clark

**Comment by FrozenPvPs** [comment]
> Then it must of been stolen or leaked, either way, our Reseller was doing something dodgy with the licensing, we used an official version from the WHMCS website. If you would like to know our other domains, you can Private Message me on Discord, as we don't want to disclose them publically.
> 
> Thanks,
> Christian Clark

Are you going to disclose your company registration number?

**Comment by Qubopp** [comment]
Ok then, I'm not posting them at all 👍

**Comment by DamonOnYT** [comment]
lmao this man tried to apply for HR positions at my company

**Comment by Qubopp** [comment]
Yeah, months ago.

**Comment by falceso** [comment]
Hello there,

Due to the ambiguous nature of this PR, we are requesting updated, clear, and concise evidence & reasoning to be posted on our new system on [Revenact](https://revenact.io/groups/summerhoax-club-tm.22/discussions). As we wish to improve the quality, of our listings, we ask you provide a professional tone quality when creating replies or new threads. 

Sincerely,
SummerHoax Team.

**Pull request closed without merging**
