### PR TITLE
rainhosting is continued as regenhosting

### PR DESCRIPTION
**Pull request by jesgeerts**

### CODE REVIEW

**Comment by Daxorinator** [comment]
Their website seems to be down, can you please post some proof of rainhosting being continued as regenhosting?

Voting to close unless evidence is dropped

**Comment by Ethereal739** [comment]
Website is online and it seems like they have a legit license?

image

**Comment by Daxorinator** [comment]
I think you commented on the wrong PR Eth ;)

**Comment by jesgeerts** [comment]
> Website is online and it seems like they have a legit license?
> 
> image

I think you've posted that in the wrong PR.

**Comment by jesgeerts** [comment]
> Their website seems to be down, can you please post some proof of rainhosting being continued as regenhosting?
> 
> Voting to close unless evidence is dropped

They went recently just back again to rainhosting.

**Pull request closed without merging**
