### PR TITLE
Add FabitHosting

### PR DESCRIPTION
**Pull request by hb4uhomebrew**
Read the PR edits

### CODE REVIEW

**Comment by hb4uhomebrew** [comment]
image

**Comment by hb4uhomebrew** [comment]
https://discord.gg/SxBVexG in the slim chance this invite gets revoked here is the invite to FabitHosting.

**Comment by Qubopp** [comment]
image
Can you DM me what can't be listed 'here' 
Gherkin#7748

**Comment by Silgica** [comment]
image

**Comment by Silgica** [comment]
http://fabithost.com/

**Comment by Qubopp** [comment]
Lmao yeah he is abusive to his customers too

**Comment by Silgica** [comment]
image
After this conversation, I was banned from the FabitHost Discord with no reason given. I had a previous DM conversation with MonkeyMax advising against him using Fabit, in which I linked him and provided screenshots of the SummerHoax entry on FalixNodes / ItzAwesome and to this PR. He stated that 2 people had already told him not to go with them.

After looking with an alt account, it appears Tommy (Ethereal) and a few other members of the Revenact Discord have also been removed.

**Comment by gtsatsis** [comment]
It's a fucking skid, Tom. I say @hb4uhomebrew cleans up their commit (list reasons, etc), and I motion to merge after that.

**Comment by DamonOnYT** [comment]
@Silgica MonkeyMax asked in the FabitHost discord what their pricing is. I sent him a DM explaining this was a summer hoax run by staff who have worked at other summerhoaxs

**Comment by Qubopp** [comment]
Personally I find it hillarious 'working' for Summerhoaxes and being on the inside and seeing how poorly these companies are run. FreeMC, isn't run poorly, but the servers, which are suprisingly co-located in South Australia (where I live) are strained so hard, I've had to go to the datacenter for NickE multiple times to do hard resets.

**Comment by nick-2017** [comment]
@Qubopp Stop spreading false information.
You aren't working for us and never have been.
We rent our free nodes from Hetzner in Germany.
We have nothing colocated and nothing running anywhere near Australia.

**Comment by DamonOnYT** [comment]
> @Qubopp Stop spreading false information.
> You aren't working for us and never have been.
> We rent our free nodes from Hetzner in Germany.
> We have nothing colocated and nothing running anywhere near Australia.

For once I actually believe you

**Comment by Patrickgae** [comment]
That being said how would you even do colocation with a free host that will be mostly unprofitable by a far.

**Comment by Qubopp** [comment]
Haha you're funny.

**Comment by Patrickgae** [comment]
Well thanks! Everyone is funny and many people have a great  personality. Also you should buy my colo.

**Comment by falceso** [comment]
@hb4uhomebrew As requested by other contributors, please develop the preview a bit more and this PR may be approved in the next round.

**Comment by BraidynR** [comment]
> @hb4uhomebrew As requested by other contributors, please develop the preview a bit more and this PR may be approved in the next round.

I completely forgot about this, I'll do it as soon as I have time.

**Comment by falceso** [comment]
Hello,

As an effort to improve the quality of this project, we are moving into a new system on [Revenact](https://revenact.io/forums/discussion.65/). Please attach the evidence, and an updated reasoning for be listed as a "SummerHoax".

Sincerely,
SummerHoax Team

**Pull request closed without merging**
