### PR TITLE
Added ICX Realty

### PR DESCRIPTION
**Pull request by FrozenPvPs**
God damn shitty host

### CODE REVIEW

**Comment by Electromaster232** [comment]
Is it true all of the ICX servers have been stolen? I know this isnt the place but since all the community's are gone that they were around.

Guess its time to call my bank and chargeback.

**Comment by KidsAreSalty** [comment]
> Is it true all of the ICX servers have been stolen (by the owner)? I know this isnt the place but since all the community's are gone that they were around.
> 
> Guess its time to call my bank and chargeback.

If I recall when he did colocation he setup contracts in a way where he owned the servers once the contract was up or something. It was a scheme from the start and he took advantage of the 80% of people who don't thoroughly read a contract.

**Comment by Ethereal739** [comment]
I don't have any sort of confirmation about server theft but I have talked to a few of their customers and yes they indeed just shut down the servers and never turned them back on. Shouldn't have removed these clowns.

**Comment by Electromaster232** [comment]
I ask because I *am* a customer and have heard that this may have happened in a WebHostingTalk post

**Pull request merged**
