### PR TITLE
Add Aaron Ward to the Vault

### PR DESCRIPTION
**Pull request by ACA30**
## Excerpt from the vault card cause I'm lazy --

> Aaron Ward, owner of Webrex Hosting, has been banned from mc-market for asking a fourteen-year-old for nudes. He made an attempt to ban evade, which failed, just like his many other attempts: including, Webrex Hosting, which has been down for multiple days. He has been losing clients faster than Voxility creates hosts, and is known to be using suicidal thoughts, depression, and a feeling of a failed investment as an excuse to keep his host open. While the validity of his depression is not verified, it is clear he is using it as an excuse to continue to create new discord and forum accounts in order to bother members of our communities.

He deserves to be added...

### CODE REVIEW

**Comment by ACA30** [comment]
(Also tbh give me SummerHoax Project / Contrib roles ;) ill do helpful things or whatever)

```Nate [ACA30]#0001 // 210762063021211649```

**Comment by Focoos** [comment]
> (Also tbh give me SummerHoax Project / Contrib roles ;) ill do helpful things or whatever)
> 
> `Nate [ACA30]#0001 // 210762063021211649`

You...you have no contributions besides this unapproved one

**Comment by ACA30** [comment]
> > (Also tbh give me SummerHoax Project / Contrib roles ;) ill do helpful things or whatever)
> > `Nate [ACA30]#0001 // 210762063021211649`
> 
> You...you have no contributions besides this unapproved one

shhhhh 'twas a danke maymay. i don't expect to get it from doing basically nothing lol

**Comment by ACA30** [comment]
Closing cause it didn't add my new commit for some reason.

**Comment by ACA30** [comment]
I'm actually slow it's not even funny...

**Comment by Steampunkrule** [comment]
+1

**Comment by TonyS95** [comment]
Pret sure he’s already added aka max p

**Pull request merged**
