### PR TITLE
Addition: MixML Hosting

### PR DESCRIPTION
**Pull request by Endeavor756**
MixML Hosting is using a logo they're not authorized to use (Mine). They're also using Gatto's Argon theme without permission.

Screen Shot 2019-05-12 at 7 52 17 PM
Screen Shot 2019-05-14 at 1 10 42 AM
Screen Shot 2019-05-14 at 1 11 44 AM
Screen Shot 2019-05-14 at 1 11 48 AM
Screen Shot 2019-05-16 at 6 56 23 AM

When confronted about it, they said they'd get rid of both but didn't.

### CODE REVIEW

**Comment by ygtripps** [comment]
Honestly this just seems like a revenge attack seeing as you left. You don't have the right to giveaway themes that aren't originally yours. Since you offered the logo for free you can't just revoke like that. Doesn't work that way as it was designed specifically for their company and you can't just say it isn't their's when you can clearly see it was made for them and them only.

**Comment by Endeavor756** [comment]
Since they said they didn't want it I have full rights to revoke their permission to use it and dispose of it. And I admit I was wrong to trust them so quickly with the theme but after the author of the theme and I approached then they said they would remove it but were lying

**Comment by Endeavor756** [comment]
And I left of my own will. If this was someone else's PR you wouldn't be saying that it's a revenge attack

**Comment by BigDaddyBanana** [comment]
> Honestly this just seems like a revenge attack seeing as you left. You don't have the right to giveaway themes that aren't originally yours. Since you offered the logo for free you can't just revoke like that. Doesn't work that way as it was designed specifically for their company and you can't just say it isn't their's when you can clearly see it was made for them and them only.
You do have a sort of point. I don’t think he has the right to give away a theme that isn’t his, furthermore it isn’t his call for you to remove it. But they are his logos and he has the rights to them, and if he wants you to remove them you need to.

**Comment by BigDaddyBanana** [comment]
> And I left of my own will. If this was someone else's PR you wouldn't be saying that it's a revenge attack

I can +1 this.

**Comment by falceso** [comment]
After a plethora of discussion with the community and CEO of the company. A change of status for this Pull request has been filed. It appears that the requested content has been handled appropriately.
 
0e01e1104164d5d

I will be closing this Pull Request in about 20 hours if no additional disputes are filed. This PR may serve as assistance in future cases, but at this time does not currently affect the ability of the company to operate with their clients in a proper and timely manner.

_If you believe, the judgment provide is unjust, feel free to interject with additional claims which cover more check-boxes for being marked as a SummerHoax in this PR._

**Comment by itsgatto** [comment]
I would like to provide additional information on this request. I feel like this host should still be added to the list, but not for the reasons that were listed. 

(Even though the owner was forced to remove the logo and the theme with a DMCA request.)

The owner has admitted to not have enough funding to run his project. 

And my question is, how are you going to run a host when you can't even spare $30 dollars and all you have is $11?

h40
(Even though the theme has been removed, I thought this might still be relevant due to him admitting his lack of fundings)

h40-2
(This one should explain by itself, he tried to lowball my work to $11 and that was his "final offer")

**Comment by Daxorinator** [comment]
+1, these guys are Summerhosts.

**Comment by BigDaddyBanana** [comment]
I like Harry, he’s always been nice and professional with me, despite that...I have to +1, this seems to be a SummerHoax to me.

**Comment by Focoos** [comment]
finally

**Comment by BigDaddyBanana** [comment]
Alright I take back what I said about Harry being a nice guy, he is the exact opposite. He will backstab you if you don’t watch your back. Earlier I asked him for a paid theme because I wanted to try it on my site. Afterwards he proceeded to ask me for thoughts on husband website which I criticized a little. While after he leaked our DMs of me asking for the theme essentially causing my graphics designer to leave. Thank you Harry for being a royal cock. Grow up please. +1 this is 100% a summer hoax.

**Comment by KidsAreSalty** [comment]
> Alright I take back what I said about Harry being a nice guy, he is the exact opposite. He will backstab you if you don’t watch your back. Earlier I asked him for a paid theme because I wanted to try it on my site. Afterwards he proceeded to ask me for thoughts on husband website which I criticized a little. While after he leaked our DMs of me asking for the theme essentially causing my graphics designer to leave. Thank you Harry for being a royal cock. Grow up please. +1 this is 100% a summer hoax.

Ignore this.. he’s just salty that he got exposed by Harry for trying to get a paid theme for free. Harry shouldn’t be added to the summerhoax list.

**Pull request closed without merging**
