### PR TITLE
Remove any notice of Wqrld because it has no proof assigned

### PR DESCRIPTION
**Pull request by Wqrld**
Remove any notice of Wqrld because it has no proof assigned (Because it's not true, I left ICX and have nothing to do with joshua sprout.)

### CODE REVIEW

**Comment by nikrozman21** [comment]
Hello. I'd like to inform you that I disagree with that. You are still affiliated with them as you still had staff roles in their Discord server not even a week ago. In addition to that you are still listed in the company's LinkedIn. Have a good day!

**Comment by mrfitnessguy** [comment]
Ill have to second this, I've been a client of ICX for a bit now and have worked with Wqrld on my systems and have worked with other ICX staff and have not seen anyone by the name of Joshua Prout. I also can confirm that Wqrld is a great system admin and fixed my dedi up for me.

**Comment by JW-Joey** [comment]
> Ill have to second this, I've been a client of ICX for a bit now and have worked with Wqrld on my systems and have worked with other ICX staff and have not seen anyone by the name of Joshua Prout. I also can confirm that Wqrld is a great system admin and fixed my dedi up for me.

Mind if i ask what your discord name is?
Kinda surprised that your github has been created like 10 minutes ago.

**Comment by mrfitnessguy** [comment]
> > Ill have to second this, I've been a client of ICX for a bit now and have worked with Wqrld on my systems and have worked with other ICX staff and have not seen anyone by the name of Joshua Prout. I also can confirm that Wqrld is a great system admin and fixed my dedi up for me.
> 
> Mind if i ask what your discord name is?
> Kinda surprised that your github has been created like 10 minutes ago.

I don't have discord but them again I still second Wqrld but I guess its going to be disregarded because I just created my github.

**Comment by Daxorinator** [comment]
@mrfitnessguy The fact your account was created 20 minutes ago, simply means that you might not be trust-worthy. The fact you deny you have a discord account, on the otherhand, is an immediate alarm bell, telling us your word means nothing. Wqrld is known to use discord for most of his work.

**Comment by JW-Joey** [comment]
> > > Ill have to second this, I've been a client of ICX for a bit now and have worked with Wqrld on my systems and have worked with other ICX staff and have not seen anyone by the name of Joshua Prout. I also can confirm that Wqrld is a great system admin and fixed my dedi up for me.
> > 
> > 
> > Mind if i ask what your discord name is?
> > Kinda surprised that your github has been created like 10 minutes ago.
> 
> I don't have discord but them again I still second Wqrld but I guess its going to be disregarded because I just created my github.

So you dont have discord, Yet you are coming to the defence of Luc. Mate. please go home
How y'all keep contact, Email ?

**Comment by Wqrld** [comment]
Thanks for the support. I don't know these people, seems like your messages to icx were enough for them to kick me out of their discord. I've also removed them from my linkedin as my current job.

**Comment by nikrozman21** [comment]
Interesting. Are you able to get an official statement from David or Katrina ?

**Comment by Wqrld** [comment]
> Interesting. Are you able to get an official statement from David or Katrina ?

sadly not, i was just kicked out from my email and the discord
If you indeed have any colocation with them i'd be sure but im not giving any statements about them

**Comment by nikrozman21** [comment]
Website edit in progess.

**Pull request closed without merging**
