### PR TITLE
Added MyServerPlanet

### PR DESCRIPTION
**Pull request by eatingenderman89**

### CODE REVIEW

**Comment by Daxorinator** [comment]
Yeah no way.

Hosts only get put on the site if they've done something illegal / highly unethical.

Having slow support and an old manager with a thirst for revenge does not warrant being on the list.

**Comment by Apexful** [comment]
Hoes mad

**Comment by eatingenderman89** [comment]
Ouch.

**Comment by Ethereal739** [comment]
We only list outright illegal, or scam or super crappy hosts. MyServerPlanet is none of this. Sure their site isn't the best, but they are not the kind of host that will run away in a few months.

**Comment by eatingenderman89** [comment]
it is crappy search it on google.

**Comment by Daxorinator** [comment]
Nobody cares if it's crappy, we only list hosts who've committed crimes or partaken in highly unethical practices.

**Comment by eatingenderman89** [comment]
Worker begs for it to be listed.

**Comment by Daxorinator** [comment]
Ok and..?

**Nothing illegal, nothing unethical.**

**Comment by eatingenderman89** [comment]
Unethical yes, Owner saying he's high and stuff manager spamming lols in the support chat. I got screenshots of all this too.

**Comment by Daxorinator** [comment]
Examples of unethical behaviour:

Denying reselling, being extremely rude to customers, running sub-par machines, scamming people.

**Not unethical behaviour:**
Being high, spamming lols

**Comment by eatingenderman89** [comment]
Little scam too, From a google review:
"
I did not receive the vps purchased more than 72 hours, they do not respond to the ticket for 2 days. Payment was authorized via paypal and was not delivered by the company. Unfortunately I can not even havaliar the service of the company because they did not even deliver the paid vps.

paid and undelivered service!
"

**Comment by eatingenderman89** [comment]
Just add them ok or I will make my own website putting them there. You don't have a choice lol.

**Comment by Daxorinator** [comment]
Go ahead and make your own website.
We're not adding them.

--LOCKED--

**Comment by eatingenderman89** [comment]
Okey

**Comment by Ethereal739** [comment]
You have no credibility but go ahead. Don't pull us into your shitty scheme like rouing does.

**Comment by eatingenderman89** [comment]
You guys ruin :D

**Comment by Apexful** [comment]
> You guys ruin :D

HOES MAD

STAY MAD 😈😈

**Comment by eatingenderman89** [comment]
Okey lol

**Comment by eatingenderman89** [comment]
Gimme discord invite

**Comment by eatingenderman89** [comment]
Haha you nubs spamming in discord for this thread to be locked.

**Comment by KidsAreSalty** [comment]
> Haha you nubs spamming in discord for this thread to be locked.

Stop spamming my email you fucking downy

**Comment by eatingenderman89** [comment]
Lol you are spamming my email too tbh

**Comment by eatingenderman89** [comment]
Worker is so sad now when you are not adding them.

**Comment by Patrickgae** [comment]
My God Welcome to github?

**Comment by Apexful** [comment]
> Lol you are spamming my email too tbh

You opened this, so expect it donkey

**Comment by eatingenderman89** [comment]
Thanks.

**Comment by eatingenderman89** [comment]
My God Welcome to Spamhub?

**Comment by eatingenderman89** [comment]
Ahahahah
"Lock the fucking thread please."

**Comment by Patrickgae** [comment]
Are you a little salty or mad?  Now please stop with your retarded responses before you make me laugh harder than I already am.

**Comment by eatingenderman89** [comment]
I enjoy making people laugh, So that's good.

**Comment by KidsAreSalty** [comment]
> I enjoy making people laugh, So that's good.

Do you enjoy life?

**Comment by Daxorinator** [comment]
Can you please go away?
We're not adding this host, your being incredibly annoying to all of us and your threats are empty.

This thread should be locked, go and make your own website like you said you were going to, instead of making stupid comments and acting salty.

**Comment by eatingenderman89** [comment]
Can you please stop replying then? It's your choice if you reply or not.

**Comment by Patrickgae** [comment]
Wait. Why are we not adding it? Lol  By his responses he deserves to be on this list.

**Comment by KidsAreSalty** [comment]
Aren’t you on summerhoax?

**Comment by eatingenderman89** [comment]
I was

**Comment by eatingenderman89** [comment]
Also if you reply i will reply so yeah haha rekt

**Comment by KidsAreSalty** [comment]
What host?

**Comment by eatingenderman89** [comment]
SuperSecretHostiThinkYouKnow

**Comment by KidsAreSalty** [comment]
I forgot lol

**Comment by eatingenderman89** [comment]
Arent you in the Pterodactyl Discord too teaching people how to install the Pterodactyl Panel for people to create summerhosts?

**Comment by KidsAreSalty** [comment]
Wait weren’t you LightFordAC?

**Comment by eatingenderman89** [comment]
I remember you hehe.

**Comment by eatingenderman89** [comment]
You are really salty but yes.

**Comment by KidsAreSalty** [comment]
Nub

**Comment by eatingenderman89** [comment]
Pruh, Sounds even worse.

**Comment by eatingenderman89** [comment]
Now worker is being almost really sad "Have you deleted it?"

**Comment by eatingenderman89** [comment]
Add me on Discord ✨eatingenderman89✨#0001

**Comment by eatingenderman89** [comment]
You should get a better life than posting summerhosts that no one will read with 1/visit a day on your website.

**Comment by Ethereal739** [comment]
> You should get a better life than posting summerhosts that no one will read with 1/visit a day on your website.

Comments locked, we do not appreciate people like you here. Please go somewhere else.

**Pull request closed without merging**
