### PR TITLE
Add MCFreeHosting LTD

### PR DESCRIPTION
**Pull request by hb4uhomebrew**
This host has screwed over another host massively & scammed my friend. Proof below.
https://cdn.discordapp.com/attachments/598253467840282664/614971738488569865/image0.png
https://cdn.discordapp.com/attachments/598253467840282664/614971739012726784/image1.png
https://cdn.discordapp.com/attachments/598253467840282664/614971739012726785/image2.png
https://cdn.discordapp.com/attachments/598253467840282664/614971829966340096/image0.png
https://cdn.discordapp.com/attachments/598253467840282664/614972420616487008/image0.png
https://cdn.discordapp.com/attachments/598253467840282664/614972420650041524/image1.png
https://cdn.discordapp.com/attachments/598253467840282664/614972421849743374/image3.png
https://cdn.discordapp.com/attachments/598253467840282664/614972422327762955/image4.png (Him going away for 3 days randomly)
https://i.imgur.com/vbyjJtC.png (Him sending my friends name & saying he suspended by VPS cause I'm friends with him.)
https://i.imgur.com/xstKWlz.png (Racial Slurs claims that it was to make a point, showing racial slurs in your host's public discord is not a good thing.) 
https://i.imgur.com/CyJp7OY.png *sighs* yet again, anti-jew jokes...

Overall this host is a terrible, unsustainable & unprofessional waste of time.

### CODE REVIEW

**Comment by hb4uhomebrew** [comment]
https://i.imgur.com/zJWaWOO.png to add, they just suspended tons of peoples accounts unsure of why, but its a good thing to add.

**Comment by nikrozman21** [comment]
I'd say PR for the racist shit, but I'm siding on the host's end for your stupid decision to host with them after your friend decided to charge-back. What else did you expect? To get a golden star for it?

Go fuck yourself if that's all you two can do in tandem.

**Comment by hb4uhomebrew** [comment]
^ data leak

**Comment by hb4uhomebrew** [comment]
> I'd say PR for the racist shit, but I'm siding on the host's end for your stupid decision to host with them after your friend decided to charge-back. What else did you expect? To get a golden star for it?
> 
> Go fuck yourself if that's all you two can do in tandem.

Me and my friend are not affiliated together in the hosting side, he charged back because he didn't recieve a whmcs key he bought from them. I had a VPS with him that they suspended because I was friends with him. I also mentioned and showed proof of racial jokes and anti-semetic jokes in public channels. I suggest reading before you hate on something like that.

**Comment by hb4uhomebrew** [comment]
He literally sells if i recall, 8GB ram for 10 euro, obviously not sustainable even more evidence that they are likely to shutdown in a few months because they wont make enough money (I WAS ADMIN THERE IVE SEEN THE AMOUNT OF CUSTOMERS THEY HAVE AND THE SPECS OF THERE SERVERS)

**Comment by GtaMasterY2** [comment]
+1 
Very unprofessional in tickets too. (Did not say I was affiliated with hoster)
image
^ Gave hosters full name through paypal chargeback image.
image
Using words like "bruh" in a professional ticket.
100GB in the server.
image
and using a VPS for hosting
image

**Comment by PmasVterP** [comment]
> +1
> Very unprofessional in tickets too. (Did not say I was affiliated with hoster)
> image
> ^ Gave hosters full name through paypal chargeback image.
> image
> Using words like "bruh" in a professional ticket.
> 100GB in the server.
> image
> and using a VPS for hosting
> image

WOAH BETTERDISCORD USER OR CUSTOM MADE OR SELFBOT. against discord tos

**Comment by PmasVterP** [comment]
Pretty sure some partnership agreement but don't know who to trust.
[https://cdn.discordapp.com/attachments/605561530565787648/614984810187849728/20190824_204749.jpg](url)

**Comment by hb4uhomebrew** [comment]
> Pretty sure some partnership agreement but don't know who to trust.
> [https://cdn.discordapp.com/attachments/605561530565787648/614984810187849728/20190824_204749.jpg](url)

My host had a partnership, stupid of me with them. They went after the partnership when my friend chargedback for something not related to my host or the partner ship deal.

**Comment by PmasVterP** [comment]
https://cdn.discordapp.com/attachments/605561530565787648/614985658364068027/20190824_205245.jpg and this too unless it's old.

**Comment by hb4uhomebrew** [comment]
> https://cdn.discordapp.com/attachments/605561530565787648/614985658364068027/20190824_205245.jpg and this too unless it's old.

This had nothing to do with VPS nodes.

**Comment by GtaMasterY2** [comment]
image
He is reading this here, hello MVP! Suspended for having an opinion. @hb4uhomebrew

**Comment by hb4uhomebrew** [comment]
Hello MVP! Your going to be famous! On Summerhoax! Yay!

**Comment by PmasVterP** [comment]
https://cdn.discordapp.com/attachments/605561530565787648/614986773637890049/20190824_205745.jpg

**Comment by JordanEMolina** [comment]
> Hello MVP! Your going to be famous! On Summerhoax! Yay!

I agree with this.

**Comment by PmasVterP** [comment]
Most free vps usually gets no backups for free etc.

**Comment by PmasVterP** [comment]
And warning on suspension.

**Comment by hb4uhomebrew** [comment]
> And warning on suspension.

It was a partner VPS, MVP obviously doesn't know how to manage it and made it public even know it was technical suppose to only be for me.

**Comment by PmasVterP** [comment]
Actually Orbital Host is it's main company.
https://cdn.discordapp.com/attachments/605561530565787648/614986773637890049/20190824_205745.jpg

**Comment by PmasVterP** [comment]
Wrong link wait

**Comment by PmasVterP** [comment]
https://cdn.discordapp.com/attachments/605561530565787648/614988266214522890/20190824_210340.jpg

**Comment by hb4uhomebrew** [comment]
What host is that? Link?

**Comment by PmasVterP** [comment]
MVP is the owner and I'm considering this to be breaking the third rule.

**Comment by hb4uhomebrew** [comment]
> MVP is the owner and I'm considering this to be breaking the third rule.

lol what, i feel your clowning. if you have nothing relavent to say, just go away ty

**Comment by PmasVterP** [comment]
https://discord.gg/GgXYCTQ this is @Two#9923 discord btw I guess I'm suppose to defend idk what to do so I'm chatting in github.

**Comment by PmasVterP** [comment]
https://cdn.discordapp.com/attachments/605561530565787648/614988927396216852/20190824_210552.jpg

**Comment by GtaMasterY2** [comment]
Straight up what the fuck? 
image

**Comment by GtaMasterY2** [comment]
image

**Comment by GtaMasterY2** [comment]
image

**Comment by PmasVterP** [comment]
First of all you should be banned from discord because of using a custom client. Second of all, you are hiding other messages that reflect you.

**Comment by GtaMasterY2** [comment]
image

**Comment by GtaMasterY2** [comment]
image

**Comment by GtaMasterY2** [comment]
image

**Comment by hb4uhomebrew** [comment]
They operate there host somewhat via WHMCS (redrock.host) but most payments for things are done via Discord. There "CEO" is MVP.

**Comment by PmasVterP** [comment]
> They operate there host somewhat via WHMCS (redrock.host) but most payments for things are done via Discord. There "CEO" is MVP.

Pretty sure lie and u have no more excuses

**Comment by PmasVterP** [comment]
https://cdn.discordapp.com/attachments/605561530565787648/614990645798502427/20190824_211244.jpg

**Comment by hb4uhomebrew** [comment]
> > They operate there host somewhat via WHMCS (redrock.host) but most payments for things are done via Discord. There "CEO" is MVP.
> 
> Pretty sure lie and u have no more excuses

Well, not like someone on the discord just said lets get this thing moving and told Etherel to merge this into summerhoax. Peace. This is goin on summerhoax ;)

**Comment by PmasVterP** [comment]
https://cdn.discordapp.com/attachments/605561530565787648/614991122774884359/20190824_211500.jpg if u wanna know where it took place

**Comment by PmasVterP** [comment]
https://cdn.discordapp.com/attachments/605561530565787648/614991122774884359/20190824_211500.jpg

**Comment by PmasVterP** [comment]
OMG WRONG LINK

**Comment by GtaMasterY2** [comment]
Yeah, I've admitted before its in a ticket. If you read it would come to your mind.

**Comment by PmasVterP** [comment]
https://cdn.discordapp.com/attachments/605561530565787648/614991695527804946/20190824_211717.jpg

**Comment by GtaMasterY2** [comment]
^ It's called reselling, money doesn't come out when you piss your dad's salt water cum.

**Comment by PmasVterP** [comment]
It's not reselling really if you give the reseller for free forever kind of. Paying a reseller is a true reseller.

**Comment by GtaMasterY2** [comment]
Okay, change the word reselling with "profit" and you will get the same answer I would post right now.

**Comment by PmasVterP** [comment]
If you want a VPS, buy it, free ones are usually not 100% reliable and someone can happen to them anytime. Be happy the host did give you a reseller to help make your host that is prob poor. (Except I have to agree your host is good and works well)

**Comment by GtaMasterY2** [comment]
What host are you talking about?

**Comment by GtaMasterY2** [comment]
https://i.imgur.com/a9cb6TQ.png

**Comment by hb4uhomebrew** [comment]
https://i.imgur.com/a9cb6TQ.png

**Comment by PmasVterP** [comment]
https://cdn.discordapp.com/attachments/605561530565787648/614991695527804946/20190824_211717.jpg

**Comment by GtaMasterY2** [comment]
Why are you copy and pasting images we have already seen?

**Comment by hb4uhomebrew** [comment]
> https://cdn.discordapp.com/attachments/605561530565787648/614991695527804946/20190824_211717.jpg

I don't understand why you keep mentioning that?

**Comment by PmasVterP** [comment]
Omfg I keep putting wrong links

**Comment by PmasVterP** [comment]
https://cdn.discordapp.com/attachments/605561530565787648/614994432613285904/20190824_212737.jpg

**Comment by PmasVterP** [comment]
https://cdn.discordapp.com/attachments/605561530565787648/614994713036193822/20190824_212912.jpg same thing technically

**Comment by GtaMasterY2** [comment]
What does having a new node mean? Are they just magically not allowed to make new clients now?

**Comment by PmasVterP** [comment]
https://cdn.discordapp.com/attachments/605561530565787648/614995848744665098/20190824_213349.jpgouCraft (owner of this post's host) is tolden that the owner is rich, clearly a lie.

**Comment by GtaMasterY2** [comment]
cool image
image

**Comment by PmasVterP** [comment]
> What does having a new node mean? Are they just magically not allowed to make new clients now?

The partnership deal ended clearly in announcements of both servers. YouCraft was given the partnership vps.

**Comment by hb4uhomebrew** [comment]
> https://cdn.discordapp.com/attachments/605561530565787648/614995848744665098/20190824_213349.jpgouCraft (owner of this post's host) is tolden that the owner is rich, clearly a lie.

If you would even know anything about hosting, server costs do not require you to be rich lol. Secondly thats clearly a joke.

**Comment by PmasVterP** [comment]
Sorry for one link not working new link: https://cdn.discordapp.com/attachments/605561530565787648/614995848744665098/20190824_213349.jpg

**Comment by PmasVterP** [comment]
> > https://cdn.discordapp.com/attachments/605561530565787648/614995848744665098/20190824_213349.jpgouCraft (owner of this post's host) is tolden that the owner is rich, clearly a lie.
> 
> If you would even know anything about hosting, server costs do not require you to be rich lol. Secondly thats clearly a joke.

I didnt think it was a joke lol... that's why I said wtf

**Comment by PmasVterP** [comment]
You are breaking the TOS of the program to used to advertise. Wouldn't that also make YouCraft a scam host?

**Comment by hb4uhomebrew** [comment]
> You are breaking the TOS of the program to used to advertise. Wouldn't that also make YouCraft a scam host?

What does that even mean? What TOS are we breaking?

**Comment by PmasVterP** [comment]
Quote from https://discordapp.com/tos

> Entire Agreement. These Terms constitute the entire agreement between you and the Company with respect to your use of the Service and any other subject matter hereof and cannot be changed or modified by you except as expressly posted on the Service by the Company. You also may be subject to additional terms and conditions that may apply when you use affiliate or third party services, third party content or third party software.

**Comment by hb4uhomebrew** [comment]
> Quote from https://discordapp.com/tos
> 
> > Entire Agreement. These Terms constitute the entire agreement between you and the Company with respect to your use of the Service and any other subject matter hereof and cannot be changed or modified by you except as expressly posted on the Service by the Company. You also may be subject to additional terms and conditions that may apply when you use affiliate or third party services, third party content or third party software.

GTAMaster does not represent us or our host. He is not staff with us.

**Comment by GtaMasterY2** [comment]
I'm not modifying, or changing Discord client either. Nice try though.

**Comment by GtaMasterY2** [comment]
It's called being a **developer**, you know, the thing you said isn't a job.

**Comment by austin81881** [comment]
Why does this even continue? We've verified he's a liar and a cheat.

**Comment by PmasVterP** [comment]
Selfbot included.

**Comment by GtaMasterY2** [comment]
It's not a self bot either. I've never used a self bot.

**Comment by PmasVterP** [comment]
> It's called being a **developer**, you know, the thing you said isn't a job.

OMG, ASK THE OFFICIAL DISCORD FEEDBACK OR TESTERS DISCORD (verified mark): https://discord.gg/discord-feedback and https://discord.gg/discord-tester

I AM A DEVELOPER TOO I KNOW MORE THAN YOU ABOUT DISCORD!!!

**Comment by GtaMasterY2** [comment]
I don't need to ask, because I'm not breaking discord rules.

**Comment by hb4uhomebrew** [comment]
> > It's called being a **developer**, you know, the thing you said isn't a job.
> 
> OMG, ASK THE OFFICIAL DISCORD FEEDBACK OR TESTERS DISCORD (verified mark): https://discord.gg/discord-feedback and https://discord.gg/discord-tester
> 
> I AM A DEVELOPER TOO I KNOW MORE THAN YOU ABOUT DISCORD!!!

Why does this have anything to do with his summerhoax? GTAMaster isn't afilliated with YouCraft.

**Comment by GtaMasterY2** [comment]
^ Exactly, and YouCraft has nothing to do with this PR pull.

**Comment by PmasVterP** [comment]
ANOTHER PROOF OTHER THAN VERIFY IS PEOPLE WITH THE RANK STAFF MOD IN THE SERVER HAVE THE DISCORD STAFF BADGE!!!

**Comment by hb4uhomebrew** [comment]
> ANOTHER PROOF OTHER THAN VERIFY IS PEOPLE WITH THE RANK STAFF MOD IN THE SERVER HAVE THE DISCORD STAFF BADGE!!!

That uh, that made no sense *laughs*

**Comment by PmasVterP** [comment]
ur breaking the tos of what program you use to help create accounts and login for the future panel

**Comment by GtaMasterY2** [comment]
> ANOTHER PROOF OTHER THAN VERIFY IS PEOPLE WITH THE RANK STAFF MOD IN THE SERVER HAVE THE DISCORD STAFF BADGE!!!

This has nothing to do with this PR, or summerhoax.

**Comment by PmasVterP** [comment]
but ur host yes and it is part of it

**Comment by austin81881** [comment]
Two, just shut your pothole. We all know it's you.

**Comment by GtaMasterY2** [comment]
> ur breaking the tos of what program you use to help create accounts and login for the future panel

I am also, not affiliated with YouCraft, or McFreeHosting at all.

**Comment by austin81881** [comment]
You're being really annoying right now. No one, and I mean NO ONE asked you to contribute.

**Comment by PmasVterP** [comment]
> > ur breaking the tos of what program you use to help create accounts and login for the future panel
> 
> I am also, not affiliated with YouCraft, or McFreeHosting at all.

i didn't know that lol

**Comment by austin81881** [comment]
Yea, he's just an innocent bystander.

**Comment by PmasVterP** [comment]
> Two, just shut your pothole. We all know it's you.

> https://discord.gg/GgXYCTQ this is @ Two#9923 discord btw I guess I'm suppose to defend idk what to do so I'm chatting in github.

clearly said who i am

**Comment by PmasVterP** [comment]
i wasn't even really paying attention to this thing that is pissing (i never use that word lol) me off

**Comment by PmasVterP** [comment]
According to me, nothing is a scam unless they do give you something and also quote from me be happy of what you have because it might be the best thing you get.

**Comment by PmasVterP** [comment]
You kept complaining and decided to report so I'm guessing "I wonder why he/she removed your node?" yah cuz ur reporting im pretty sure MVP would keep not sure but I think he wouldve if you didnt start all of this

**Comment by PmasVterP** [comment]
I'm just gonna code.

**Comment by austin81881** [comment]
I told MVP to give me my whmcs license multiple times. Do you understand that I've waited weeks for the key, and it doesn't even take 1 week to get 1 key. Literally get out my lobby.

**Comment by austin81881** [comment]
Whoops, thought we were playing fortnite there.

**Comment by GtaMasterY2** [comment]
cringeeeee

**Comment by PmasVterP** [comment]
Ask rn and tell MVP to give you ur key, unless you already refunded in some way or else you'll prob never get it.

**Comment by PmasVterP** [comment]
> cringeeeee

clearly what i feel like rn

**Comment by PmasVterP** [comment]
> Whoops, thought we were playing fortnite there.
(who plays fortnite lol)
off topic xd

**Comment by austin81881** [comment]
Dude, I don't want it now. He gave it to Ashley. So what's the point of getting it now? Answer the question briefly.

**Comment by PmasVterP** [comment]
> You're being really annoying right now. No one, and I mean NO ONE asked you to contribute.

I ask myself... I don't want the host have something bad on it (trying not to curse lol, why do i say lol), it has been scammed so many times a long time ago (stealing money people, stealing nodes, taking over, share holders greif, etc)... this is why im defending

**Comment by austin81881** [comment]
Defend yourself, not the server. Im ngl its shit and if you keep defending, you will be apart of that "**shit**"

**Comment by hb4uhomebrew** [comment]
> > You're being really annoying right now. No one, and I mean NO ONE asked you to contribute.
> 
> I ask myself... I don't want the host have something bad on it (trying not to curse lol, why do i say lol), it has been scammed so many times a long time ago (stealing money people, stealing nodes, taking over, share holders greif, etc)... this is why im defending

lol what host are u talking about

**Comment by GtaMasterY2** [comment]
> > > You're being really annoying right now. No one, and I mean NO ONE asked you to contribute.
> > 
> > 
> > I ask myself... I don't want the host have something bad on it (trying not to curse lol, why do i say lol), it has been scammed so many times a long time ago (stealing money people, stealing nodes, taking over, share holders greif, etc)... this is why im defending
> 
> lol what host are u talking about

MCFreeHosting

**Comment by NighthawkTwitch** [comment]
they screwed over a hosting company that I love. am i mad at them? oh you better believe that I'm mad.

**Comment by GtaMasterY2** [comment]
> they screwed over a hosting company that I love. am i mad at them? oh you better believe that I'm mad.

and then he hacked the cia

**Comment by NighthawkTwitch** [comment]
if he actually did that, i wouldn't be surprised one bit. did they screw you over, GTA?

**Comment by fantratic** [comment]
Lmao, they were acting unprofessional to him, that's about it. Most likely they did.

**Comment by PmasVterP** [comment]
It's a unprofessional host. i think at least

**Comment by fantratic** [comment]
> It's a unprofessional host. i think at least

Yea, sure. And which host are you talking about?

**Comment by PmasVterP** [comment]
totally free mc

**Comment by TheDeathStreamer** [comment]
This hosting service is absolutely terrible, and by the pictures I'm seeing, I wouldn't want to hear the name of this host. Like wtf kind of owners do this shit, they need to calm their shit.

**Comment by fantratic** [comment]
> This hosting service is absolutely terrible, and by the pictures I'm seeing, I wouldn't want to hear the name of this host. Like wtf kind of owners do this shit, they need to calm their shit.

Welcome TheDeathStreamer :)

**Comment by PmasVterP** [comment]
it always looks bad on greif/raid/report it happened to me now 4th time.

**Comment by fantratic** [comment]
Yea. No shit

**Comment by GtaMasterY2** [comment]
> if he actually did that, i wouldn't be surprised one bit. did they screw you over, GTA?

I was screwed out of unmetered hosting with master because I was connected to Fantratic, then was terminated a second time for commenting on a summerhost PR.

**Comment by BlakeS16** [comment]
Hope ya all enjoyed this as much as I did reading

**Comment by fantratic** [comment]
Yea fuck off MVP.

**Comment by MVPlel** [comment]
lol

**Comment by fantratic** [comment]
You're a piece of shit scmamer.

**Comment by MVPlel** [comment]
I was not the one to charge back

**Comment by fantratic** [comment]
"lol" yea join revenact.

**Comment by hb4uhomebrew** [comment]
> lol

lol

**Comment by GtaMasterY2** [comment]
> > lol
> 
> lol

lol

**Comment by fantratic** [comment]
I CHARGED BACK BECAUSE YOU DIDNT GIVE ME MY FUCKING KEY LIKE I ASKED.

**Comment by MVPlel** [comment]
lets rephrase that you spammed my inbox when the licence was pending not much I can do until they activate it.

**Comment by fantratic** [comment]
it doesnt take a fucking week to activate a license.

**Comment by NighthawkTwitch** [comment]
it takes 5 seconds.

**Comment by MVPlel** [comment]
Nah it took 4 days I was at work 11-close today

**Comment by fantratic** [comment]
and i didnt spam an **inbox** i spammed a dm.

**Comment by NighthawkTwitch** [comment]
oh no you had to close

**Comment by fantratic** [comment]
Its instant-1 day. What are you on? Weed?

**Comment by MVPlel** [comment]
What's Instant the place I get it from is not

**Comment by fantratic** [comment]
Ohhhh so you dont receive it from whmcs officially? How nice

**Comment by MVPlel** [comment]
How very nice your the one who wanted it cheap you also had free vps's with us x3 of them and free reseller and still kept asking for extras

**Comment by fantratic** [comment]
Send me my 3 bucks and I'll cancel the chargeback. Since you gave ashley the key

**Comment by MVPlel** [comment]
Keys in use you asked me to send it to him

**Comment by fantratic** [comment]
I said don't send it to him send it to me. You clearly reworded my message.

**Comment by fantratic** [comment]
And then you keep a racist staff? How amazing.

**Comment by hb4uhomebrew** [comment]
> Hope ya all enjoyed this as much as I did reading
Sure did!
DramaAlert nation now at over 5,302,874 subscrriibberrssss

**Comment by PmasVterP** [comment]
Epic

**Pull request merged**
