### PR TITLE
Issue with Routes Resolved

### PR DESCRIPTION
**Pull request by DCunninghamICX**
Issue with our routes have been resolved requesting ICX be completely removed from summerhoax.com 

https://imgur.com/a/eBf1PAA
https://imgur.com/a/2FjkefI
https://imgur.com/a/ltI9Kaf

### CODE REVIEW

**Comment by DCunninghamICX** [comment]
Issue with our routes have been resolved requesting ICX be completely removed from summerhoax.com 

https://imgur.com/a/eBf1PAA
https://imgur.com/a/2FjkefI
https://imgur.com/a/ltI9Kaf

**Comment by nikrozman21** [comment]
Hello David. Are you able to provide that in a screenshare ?

**Comment by DCunninghamICX** [comment]
Provide via screenshare? Why do you think I am posting fake information? The issues are resolved. Your welcome to join our discord and ask the clients who submitted this information to me. Its clear as day the routes are resolved.

**Comment by nikrozman21** [comment]
I'm asking for a really simple thing here.

**Comment by DCunninghamICX** [comment]
A really simple thing I do not have time to do. I'm a really busy person and my is valuable. I've already taken the time to dismantle all the wrong information you guys had about us on the website. 

The rest f the proof needed is here and posted above. Again you guys never want to do your own due diligence and simple remove information that is wrong and misleading or fixed. 

You guys have people with services with us that can verify this on the summerhoax staff. For once if someone at summerhoax can just do their job and do your own due diligence and remove us.

**Pull request closed without merging**
