### PR TITLE
Create .htaccess

### PR DESCRIPTION
**Pull request by DefinitelyNotJosh**
Otherwise the 404 page won't work.

### CODE REVIEW

**Comment by falceso** [comment]
Placing this issue **On Hold** as we currently use Nginx rather than Apache. No idea if we should route thru Config or `.htaccess`.

**Comment by DefinitelyNotJosh** [comment]
Might want to add the following to your NGINX conf then @Ethereal739:

`error_page   404  =  /404.html;`

**Comment by nikrozman21** [comment]
I believe we should first get a decent 404 page done.

**Comment by DefinitelyNotJosh** [comment]
I already have, lol.

**Comment by nikrozman21** [comment]
Reasonable enough.

**Comment by DefinitelyNotJosh** [comment]
Check the PR's comments, already have.

**Comment by nikrozman21** [comment]
That's not how you fix a PR

**Comment by DefinitelyNotJosh** [comment]
You don't put that line in the .htaccess lol, it goes in the NGINX config file. I've let Thien know what to put in there.

**Comment by nikrozman21** [comment]
I know you don't. That's the exact reason why I told you to fix up the PR and make it NGINX compatible.

**Comment by DefinitelyNotJosh** [comment]
But there's no need for an .htaccess then?

**Comment by nikrozman21** [comment]
No, Josh. There's no need for it.

**Comment by DefinitelyNotJosh** [comment]
So why are you asking me to fix the PR?

**Comment by DefinitelyNotJosh** [comment]
So why are you asking me to fix the PR?

**Comment by Daxorinator** [comment]
Christ almighty you are thick.

**Comment by TonyS95** [comment]
You need to fix it because the pr is creating a .htaccess instead of nginx.conf and if he pushed the pr it will create a .htaccess and it'll fuck up most likely.

**Comment by DefinitelyNotJosh** [comment]
I don't want this PR to be pushed, it's simply a notice/reminder for Thien to update the NGINX config.

**Comment by Patrickgae** [comment]
Thank you for your order. Your order is now placed.

**Comment by DefinitelyNotJosh** [comment]
Thanks Patrick, this is the first time I've tried AccuratePizza™

**Comment by nikrozman21** [comment]
Alright. Have a nice day then.

**Comment by DefinitelyNotJosh** [comment]
Keep this open, I need Thien to see it.

**Comment by ygtripps** [comment]
No this will remain closed as we will never use Apache in any fucking sense.

**Comment by DefinitelyNotJosh** [comment]
I know that lmao, that's why if you read up I've provided Thien with the NGINX config directive.

**Comment by ygtripps** [comment]
Josh we don't need help in regards to the webserver configurations. We have like 3-4 sysadmins on the project team, the only thing we need help with is the articles not the physical bullshit behind the site.

**Comment by DefinitelyNotJosh** [comment]
I've only posted this here to REMIND him.

**Comment by ygtripps** [comment]
But I mean he doesn't need to reminded when we already are annoying the fuck out of him with other shit. Thanks again, but not needed :)

**Comment by TonyS95** [comment]
This can be closed. https://github.com/summerhoax/summerhoax.github.io/pull/35

**Comment by DefinitelyNotJosh** [comment]
I'm simply doing what Falcesco said. The PR is already closed.

**Pull request closed without merging**
