### PR TITLE
WIP: Add BiSoga

### PR DESCRIPTION
**Pull request by gtsatsis**
**Notice: BiSoga is a file host, not a hosting company**.

BiSoga seems to not accept criticism, beginning from a Freenom domain (biso.ga), they evolved into "creating their own tablet", which is nothing but a scam OEM tablet.

All the shit they do can be seen on their Discord server, which a permalink to can be found on their site, https://bisoga.xyz

I'll attach screenshots later on, but until then, you can just see this shit on their Discord.

*Notice:* While it is true, that I am the administrator and owner of RATELIMITED, yet another file hosting provider, this pull request is being made without bias toward my hosting services, and as seen below in the comments, a BiSoga user does agree with what is being said.

### CODE REVIEW

**Comment by gtsatsis** [comment]
They are allegedly using the Discord CDN to handle file uploads, and they seem to be always denying it, but when the Discord CDN went down, they went down as well/

**Comment by ThePixelord** [comment]
> Addendum #3:
> They claim that they are making a custom tablet (as can be seen on their Discord, from Will's messages, as well as their Kickstarter, which I've archived here: http://web.archive.org/save/https://www.kickstarter.com/projects/bisoga/bablet-the-bisoga-tablet).

You saved the 'Save page' link for their tablet. 🤦‍♂

**Comment by gtsatsis** [comment]
> 
> 
> > Addendum #3:
> > They claim that they are making a custom tablet (as can be seen on their Discord, from Will's messages, as well as their Kickstarter, which I've archived here: http://web.archive.org/save/https://www.kickstarter.com/projects/bisoga/bablet-the-bisoga-tablet).
> 
> You saved the 'Save page' link for their tablet. man_facepalming

I don't exactly know how to use The Web Archive, so if it's possible, correct me please.

**Comment by ThePixelord** [comment]
> > > Addendum #3:
> > > They claim that they are making a custom tablet (as can be seen on their Discord, from Will's messages, as well as their Kickstarter, which I've archived here: http://web.archive.org/save/https://www.kickstarter.com/projects/bisoga/bablet-the-bisoga-tablet).
> > 
> > 
> > You saved the 'Save page' link for their tablet. man_facepalming:
> 
> I don't exactly know how to use The Web Archive, so if it's possible, correct me please.

I haven't been able to save a copy of the page either. For anybody reading, [this](https://www.kickstarter.com/projects/bisoga/bablet-the-bisoga-tablet) link is still active, but funding's been suspended by Kickstarter.

Also, as additional information for people to bear in mind, Bisoga's a large rival with Tsatsis' host (ratelimited).

**Comment by gtsatsis** [comment]
> Also, as additional information for people to bear in mind, Bisoga's a large rival with Tsatsis' host (ratelimited).

This is actually nothing to do with RATELIMITED, just personal opinion lmao

**Comment by gtsatsis** [comment]
image

Is Will *really* that immature?

**Comment by anishanne** [comment]
We have to take into account that BiSoga is RLME (@gtsatsis )'s rival. However, as a BiSoga user, I agree with most of the claims being made here.

**Comment by gtsatsis** [comment]
> 
> 
> We have to take into account that BiSoga is RLME (@gtsatsis )'s rival. However, as a BiSoga user, I agree with most of the claims being made here.

I'd once again like to point out that RLME has nothing to do with this, but thank you for agreeing.

**Comment by anishanne** [comment]
The thing is, its not uncommon for companies to try to make their rivals look bad. However, in this case I fully agree that BiSoga should be blacklisted.

**Comment by Electromaster232** [comment]
Fairly unimportant to merging (which I believe you should), but they have changed the story on their "bablet" a few times now, as you can see here they claim Android 8.1, yet on Kickstarter it is 7.0.0 https://cdn.discordapp.com/attachments/444643641349373952/634534800577003531/unknown.png
And of course their "bablet CADs" are just hand drawings on printer paper (not good hand drawings, mind you. I'd get it if they did it on graph paper and maybe used a ruler or something but this clearly looks like the work of a child)

**Comment by anishanne** [comment]
> Fairly unimportant to merging (which I believe you should), but they have changed the story on their "bablet" a few times now, as you can see here they claim Android 8.1 (and admit to it being an OEM rebrand, which they tried to hide at the beginning), yet on Kickstarter it is 7.0.0 https://cdn.discordapp.com/attachments/444643641349373952/634534800577003531/unknown.png
> And of course their "bablet CADs" are just hand drawings on printer paper (not good hand drawings, mind you. I'd get it if they did it on graph paper and maybe used a ruler or something but this clearly looks like the work of a child)

Agreed, it looks like something a 10 year old drew on a piece of paper in 30 minutes. https://file.coffee/cGC_WL44R8.jpg

**Comment by Qubopp** [comment]
Owner is clearly about 12: https://www.youtube.com/watch?v=yDV-DGGlAac

**Comment by codepupper** [comment]
> Owner is clearly about 12: https://www.youtube.com/watch?v=yDV-DGGlAac

13 last time I've heard, but yes.

> We have to take into account that BiSoga is RLME (@gtsatsis )'s rival. However, as a BiSoga user, I agree with most of the claims being made here.

No, we don't have to do that really? Sure, rlme is bisoga's rival, but so is every other image host, like OwO or literally any Lolisafe Host.

I'd personally like to point out that Will literally insulted me on his "business"/"corporate" account on twitter, for sending a link to the same product but on Amazon or smth.
Also: He banned the MagicCap creator because he thought that he was starting Drama, even though Jake ( the creator ) was literally just trying to add them to his App.

**Comment by aidenjay345** [comment]
I would also like to just point out that the upload limit is the same as Discords.

**Comment by samicrusader** [comment]
toobig

I like how they don't go over 8 MB, yet they mock Discord in an [old promo video](
https://cdn.glitch.com/730e266f-6275-4997-bba3-1abe5b023012%2FBiSoga%20Demo%20Video.mp4?1554839149072) for the 50MB limit for Nitro users (0:16 in the video)

**Comment by aidenjay345** [comment]
Will & Advaith also leak people's IP's in the general chats, but logging the IP's when people upload files, and then using his discord bot, he is able to just announce it for everyone to see. 

image

**Comment by anishanne** [comment]
Erm, widget bot is run by a completely different company... Basically, when people talk on BiSoga via widgetbot it logs there IP. More info: https://widgetbot.io

https://file.coffee/04OI8cEBLX.png

**Comment by aidenjay345** [comment]
There are multiple projects on advaith's glitch labeled "widgetbot" that leads me to belive he is running a copy of it. 
The server also have like a million bot accounts named WidgetBot
Here are all the ID's 

Widget bot {
454690769010425856
543225764036870167
454690519952523267
604056212706689076
565479321247154186
356856478495408129
448938922467262474
514121493345730564
565479321247154186
}

**Comment by anishanne** [comment]
Please do some research, Advaith is part of the widgetbot team so it's natural that he has access lots of versions of the bot. I think he wants to use bisoga as a testing ground? Whatever it may be, **bisoga is not tracking & exposing User IP's via file uploads.**

**Comment by aidenjay345** [comment]
The Network tab shows a request being made to disweb.dashflo.net on file upload. this is why I think it does log you IP on file upload.

**Comment by anishanne** [comment]
Ya that's the Widgetbox widget in the bottom right corner?

**Comment by NotNite** [comment]
Actually, I'd like to interject for a moment.

There is an unlisted channel in BiSoga's Discord named #harry-berries, which receives a new message each time a message is uploaded. The channel and latest message's ID is exposed, but the contents are not, so this is purely speculation.

They have claimed it is a "logging channel" (why would you need to log each image? is the image EMBEDDED in the log?) but I believe it is the channel where they upload images to for storage.

If it is a logging channel, it could perhaps show the image you have uploaded to staff, or contain stuff like IPs. If not, it's still a channel that contains *every image uploaded to BiSoga*.

**Comment by samicrusader** [comment]
when people use widgetbot, it will store the user IP identifying the user from the discord OAuth login.

this may be a feature to prevent abuse but it can be used for tracking uploads on the bisoga site if you were already logged in, since requests can be logged server-side, and if you upload or say something they don't like, the bots ability to pull up IPs on something that isn't a web panel can be used to dox an individual, even if they did nothing wrong.

it's a good concept, it's just in advaith's hands (or the wrong hands).

**Comment by gtsatsis** [comment]
> Please do some research, Advaith is part of the widgetbot team so it's natural that he has access lots of versions of the bot. I think he wants to use bisoga as a testing ground? Whatever it may be, **bisoga is not tracking & exposing User IP's via file uploads.**



> Will & Advaith also leak people's IP's in the general chats, by logging the IP's when people upload files. Then using his discord bot, he is able to just announce it for everyone to see.
> 
> image

@anishanne, from the screenshot, you can clearly see that Advaith leaked the IP of a user through a Widgetbot command, in a public channel.

That *does not necessarily mean* that BiSoga is logging IPs on upload, although, it is known that they log IPs through Cloudflare's firewall, anyways. It's correlatable data, but it's a big stretch, because whoever uses Cloudflare has that feature.



> > Owner is clearly about 12: https://www.youtube.com/watch?v=yDV-DGGlAac
> 
> 13 last time I've heard, but yes.
> 
> > We have to take into account that BiSoga is RLME (@gtsatsis )'s rival. However, as a BiSoga user, I agree with most of the claims being made here.
> 
> No, we don't have to do that really? Sure, rlme is bisoga's rival, but so is every other image host, like OwO or literally any Lolisafe Host.
> 
> I'd personally like to point out that Will literally insulted me on his "business"/"corporate" account on twitter, for sending a link to the same product but on Amazon or smth.
> Also: He banned the MagicCap creator because he thought that he was starting Drama, even though Jake ( the creator ) was literally just trying to add them to his App.

1. Yes, Will seems to be 13.
2. I agree with this statement (lol)
3. Will has proven incapable of being professional/serious on many occasions, and this was one of them. If you have screencaps, feel free to post.
4. Will seems to be a trigger-happy idiot, he'll ban anyone for anything that goes against his opinions.

**Comment by gtsatsis** [comment]
BiSoga planning to *raid* RATELIMITED, and literally tweeting about it (le sigh):
Screenshot_20191011-143319_Twitter

@falceso I'm currently trying to get more of the screenshots, but most seem to be on my old phone, which is on its last breaths, I've contacted a few other people that have more screenshots, but until then, yeah.

**Comment by Qubopp** [comment]
Motion to merge

**Comment by anishanne** [comment]
> > Please do some research, Advaith is part of the widgetbot team so it's natural that he has access lots of versions of the bot. I think he wants to use bisoga as a testing ground? Whatever it may be, **bisoga is not tracking & exposing User IP's via file uploads.**
> 
> > Will & Advaith also leak people's IP's in the general chats, by logging the IP's when people upload files. Then using his discord bot, he is able to just announce it for everyone to see.
> > image
> 
> @anishanne, from the screenshot, you can clearly see that Advaith leaked the IP of a user through a Widgetbot command, in a public channel.

It was the API of a user who used the website to send a message. As you can see in the screenshot, adviath **provided a message ID**, not a user id. So advaith leaked the IP of a user using the widgetbot function on BiSoga which can't be linked to a single Discord User. 

Other than that the rest of your facts are pretty spot on.

**Comment by gtsatsis** [comment]
@anishanne, while I do agree, I have to also state that, leaking **anyone's** IP is a bad idea, especially if it is in a general chat.

The act is what matters, not exactly if it can or can't be linked to a specific Discord user, as they're still a *widgetbot user*.

*Just to note, a User can be many things, including an individual using a different service than Discord alltogether, hence why the word User was used*

Ps. User user used use user user user use used, just because there's so many "use*"'s in this it's just funny lol

**Comment by anishanne** [comment]
@gtsatsis Basically, he's leaking the IP of someone using widgetbot widget on BiSoga. We can't link this IP to a Discord user so it's fairly useless.

**Comment by gtsatsis** [comment]
@anishanne, I'm aware, I'm just clarifying that such an action is foolish, and that should have never happened to begin with.

After all, the only thing one could do with an IP is just boot someone offline nowadays, and if that.

The matter of this PR, though, is the BiSoga tablet and the Discord CDN accusations along with the owner's immaturity, let's not make it entirely about leaking someone's ip.

**Comment by aidenjay345** [comment]
The IP is linked to the user! In the screenshot, it shows the username of the person who sent the message!

**Comment by anishanne** [comment]
> The IP is linked to the user! In the screenshot, it shows the username of the person who sent the message!

That's the name the user picked when they decided to use widget bot....

**Comment by aidenjay345** [comment]
This data can still be used to identify a user.
If I went to use widget bot and I put in my real username ACFC, and called will a do-do head. He could leak my ip, and people would know its. me.

**Comment by anishanne** [comment]
> This data can still be used to identify a user.
> If I went to use widget bot and I put in my real username ACFC, and called will a do-do head. He could leak my ip, and people would know its me.

But there's no proof that it's you. It could be someone else that put your name in. **There's no solid proof** is basically what I'm saying.

This whole argument can't be proven but its just evidence that seems too big to be a coincidence..

**Comment by aidenjay345** [comment]
It does not matter who is behind it.
The fact of the matter is that he has access to people's IP's. and will openly post them in public. 
Its not about who owns that ip, but the act of them doing it.

**Comment by advaith1** [comment]
A guest user spammed so I was getting their IP to ban them.

Widgetbot users are not related to bisoga users and we do not store ips for file uploads.

@samiscrusader widgetbot does not have discord oauth, guest users are not connected to discord users

**Comment by samicrusader** [comment]
> A guest user spammed so I was getting their IP to ban them.
> 
> Widgetbot users are not related to bisoga users and we do not store ips for file uploads.
> 
> @samiscrusader widgetbot does not have discord oauth, guest users are not connected to discord users

Ah, I thought you needed to authenticate to WidgetBot, from what I saw on it's website. Apologies.

**Comment by advaith1** [comment]
The v2 beta has authentication but it doesn't expose ips

**Comment by samicrusader** [comment]
> The v2 beta has authentication but it doesn't expose ips

Is that what's deployed on https://widgetbot.io/? or is that a completely separate site?

**Comment by advaith1** [comment]
Yeah widgetbot.io is running the beta

**Comment by samicrusader** [comment]
> Yeah widgetbot.io is running the beta

That makes more sense.

**Comment by codepupper** [comment]
Advaith, ily bro but I'm still all for adding Bisoga to this. The way Will is running it is the most scummy and scammy I've ever seen, *and Adam and I have been scammed by a Datacenter before*.

Bisoga is killing itself, or well. Will is killing Bisoga the way he's running it. The fact that you even had to delete Will's Insulting tweets to me, shows that Will is literally not ready to run a business / corporation or what ever he wants to call it. 
He said himself that there are no trademarks on Bisoga, yet there's multiple times bisoga sites say "Trademark Bisoga" or "Bisoga is a Trademark of Will [Lastname]"

I'd honestly love to see Bisoga grow and maybe use it one day, but currently everything about it seems rather scummy and really fitting for summerhoax.

**Comment by anishanne** [comment]
> Advaith, ily bro but I'm still all for adding Bisoga to this. The way Will is running it is the most scummy and scammy I've ever seen, _and Adam and I have been scammed by a Datacenter before_.
> 
> Bisoga is killing itself, or well. Will is killing Bisoga the way he's running it. The fact that you even had to delete Will's Insulting tweets to me, shows that Will is literally not ready to run a business / corporation or what ever he wants to call it.
> He said himself that there are no trademarks on Bisoga, yet there's multiple times bisoga sites say "Trademark Bisoga" or "Bisoga is a Trademark of Will [Lastname]"
> 
> I'd honestly love to see Bisoga grow and maybe use it one day, but currently everything about it seems rather scummy and really fitting for summerhoax.

That's the problem, @advaith1 is amazing, runs the server properly, does backend nicely etc. But will is COMPLETELY DESTROYING BiSoga and at this rate it might as well be considered a hoax.

**Comment by codepupper** [comment]
> That's the problem, @advaith1 is amazing, runs the server properly, does backend nicely etc. But will is COMPLETELY DESTROYING BiSoga and at this rate it might as well be considered a hoax.

Exactly!

**Comment by advaith1** [comment]
Bablet has been abandoned

**Comment by anishanne** [comment]
> Bablet has been abandoned

If you want BiSoga to not miserably fail I suggest you add Will to the list of abandoned things.

**Comment by NotNite** [comment]
> If you want BiSoga to not miserably fail I suggest you add Will to the list of abandoned things.

lol

**Comment by anishanne** [comment]
> > If you want BiSoga to not miserably fail I suggest you add Will to the list of abandoned things.
> 
> lol

Let's be honest, Will is the only reason we are having this conversation right now. I'm sure @gtsatsis can agree with me.

**Comment by falceso** [comment]
Hello there!

Thanks for considering adding BiSoga, to the SummerHoax list. To simply the information provided, we ask you attach your evidence & reasoning into a thread on [Revenact](https://revenact.io/forums/discussion.65/).

We ask you provide a professional tone quality when creating replies or new threads.

Sincerely,
SummerHoax Team

**Pull request closed without merging**
