### PR TITLE
Was told to do this to add panel.rapidmc.xyz

### PR DESCRIPTION
**Pull request by AshleyHunter01**

### CODE REVIEW

**Comment by Ethereal739** [comment]
I mean, I told you to make a PR adding them to the code, not this.

**Comment by AshleyHunter01** [comment]
Sorry ill try do that now as I’m on mobile

**Comment by hb4uhomebrew** [comment]
Are you IPvD...

**Comment by AshleyHunter01** [comment]
Got an issue with me been IPvD?

**Comment by AshleyHunter01** [comment]
Pushing changes in a few mins btw

**Comment by hb4uhomebrew** [comment]
Yes. You are affiliated with MVP and his scamhosts. You have no right coming in here and PRing other hosts fuck off with ur ipvd host lookin ass.

**Comment by AshleyHunter01** [comment]
I have the right to do what i want. Haters gonna hate

**Comment by hb4uhomebrew** [comment]
No, People will hate on scammers like yourself. Now fuck off.

**Comment by hb4uhomebrew** [comment]
I do not like rapid, i hate you.

**Comment by MCKingSam** [comment]
Screenshot_20191009-205418_Discord

**Comment by AshleyHunter01** [comment]
Too late sam :)

**Comment by hb4uhomebrew** [comment]
these dumb shits love to try to keep themself off summerhoax by contributing, actually go the fuck away ashley.

**Comment by hb4uhomebrew** [comment]
you all should be on summerhoax imo

**Comment by AshleyHunter01** [comment]
Lol

**Comment by hb4uhomebrew** [comment]
What's your host, by the way.

**Comment by hb4uhomebrew** [comment]
Your host is already on summerhoax, nvm. go away

**Comment by AshleyHunter01** [comment]
It isnt lol

**Comment by hb4uhomebrew** [comment]
its gonna be <3

**Comment by AshleyHunter01** [comment]
My host has not done anything wrong and ethearal was in my hosts discord and its legit

**Comment by hb4uhomebrew** [comment]
Eh I have some dirt, your host will be on summerhoax eventually.
ik ur lookin at this ethereal dm me :D

**Comment by AshleyHunter01** [comment]
Cool you have dirt GG!! My host is legit and will remain that way

**Comment by MCKingSam** [comment]
Ashley you tried to refund £3.. you obviously have no money. I even had to show you pictures of my money... your so dumb

**Comment by AshleyHunter01** [comment]
Because my other cash was sent from my old deleted paypal and when i asked for half my cash you refused, enjoy summerhoax

**Comment by hb4uhomebrew** [comment]
ur all summerhoax's fuck off

**Comment by MCKingSam** [comment]
We dont offer refunds.

**Comment by AshleyHunter01** [comment]
You did not state that when i bought my product, its funny how you wont even give me half my cash

**Comment by MCKingSam** [comment]
It was classed as a "donation" and you well knew that.

**Comment by MCKingSam** [comment]
Also you raided QT and I's discord server which made me angry.

**Comment by MCKingSam** [comment]
No you didnt you well knew it was classed as a donation so technically you could have received nothing.

**Comment by AshleyHunter01** [comment]
Proof i raided?  And i did not know it was a donation so stop being a scammer and give me my cash

**Comment by MCKingSam** [comment]
Yes you did, you told me you didnt want the server. You well knew it was a donation stop lying just to try and get your cash back. It isnt working ash

**Comment by AshleyHunter01** [comment]
1) Dont want a server as i dont trust you with my files, 2) did not know it was a donation i paid for something you couldnt even make last 2 weeks 3) stop scamming people.

**Comment by PmasVterP** [comment]
Actually, you raided the server before all of this happened. Your Discord account already has been reported by MULTIPLE people, even before the raid. We (not RapidHost, like the community people hating on Ashley, even people that know, knew or doesn't know you) have enough evidence and your Discord account is eventually going to ban you. This is not related to RapidHost, but this is something I was going to DM Ashley, but he blocked me. Also, you threatened to DDOS me. Nice to know.

**Comment by PmasVterP** [comment]
btw you decided to ban me in every I was in that you can ban me in, which was also against the staff rules... and also stop making alts because it is annoying. 

You also took my closed source Discord bot project, you clearly didn't know the LICENSE, why would anyone trust you. Ashley DM me on Discord and stop being too scared and left that server cuz you couldn't ban me

**Comment by AshleyHunter01** [comment]
Did not threaten to ddos you i told you to pipe the fuck down and i do not have your bot code as i never backed it up so shut the fuck up and go play with your legos

**Comment by MCKingSam** [comment]
Btw Ashley are toy Male or female? I couldnt tell by your picture

**Comment by AshleyHunter01** [comment]
Male.

**Comment by HBIDamian** [comment]
Now that that piece of information is out, people on the discord (looking at you IOSpaceBar 😂) can stop saying SHE. 
Ashley is commonly a male name, although it is a unisex name xD

**Comment by MCKingSam** [comment]
Well I personally couldn't tell by the picture I saw

**Comment by SoyDark** [comment]
https://cdn.discordapp.com/attachments/630186984509538325/631963651984850964/unknown-1.png

**Comment by Qubopp** [comment]
image

**Comment by AshleyHunter01** [comment]
My bio is a joke a friend set it and i never changed it

**Comment by MCKingSam** [comment]
Lmfaoo

**Comment by AshleyHunter01** [comment]
I don’t see a point in changing it as I only use github for my private repos

**Comment by Qubopp** [comment]
Not gonna lie you do actually look like a girl

**Comment by AshleyHunter01** [comment]
K why we still talking on here it was closed lol

**Comment by Qubopp** [comment]
dunno lmao

**Pull request closed without merging**
