### PR TITLE
Create 404.html

### PR DESCRIPTION
**Pull request by DefinitelyNotJosh**
;)

### CODE REVIEW

**Comment by DefinitelyNotJosh** [comment]
Sorry for the delay, unfortunately I'm not proficient in HTML nor CSS so uh... you might want to find someone else.

**Comment by falceso** [comment]
> Sorry for the delay, unfortunately I'm not proficient in HTML nor CSS so uh... you might want to find someone else.

Trial and Error is a good learning technique in HTML. 😉 I've theoretically provide the necessary code snippets to successfully clear my review.

**Comment by DefinitelyNotJosh** [comment]
I'll take a look later, currently on phone.

**Comment by DefinitelyNotJosh** [comment]
Oops, sorry.

**Comment by DefinitelyNotJosh** [comment]
See new PR.

**Pull request closed without merging**
