### PR TITLE
Update index.html

### PR DESCRIPTION
**Pull request by DCunninghamICX**
The IP's / ASN do not match what so ever the information is false. A quick google search would prove that, again please do adequate research.

### CODE REVIEW

**Comment by DCunninghamICX** [comment]
In regards to ICX being on summerhoax it looks like the last issue is our network. 

That issue I believe still exist depending on where the routes to and from a certain area. EU routes are still pretty screwed up to the brutally honest. However were adding a few peering locations to bridge the gaps.

We do have a solution for the traffic from point A - B. 

As explained to Perhaps - 

Well the response we received from Cogent is TATA is the only route they have to and from that specific location and once they hand off to TATA nothing more they can do. We tested a resolved by removing the route to TATA and the ms went even higher. So the only other thing for us to do is add a few other peering locations which as you might know is not an easy task when it comes to equipment ordering, cross connects and location in general its not an overnight task.

Requesting ICX be removed from Summerhoax on ground of everything listed on the website has either been resolved, found to be lies or pending resolution. 

Thank you.

**Comment by DefinitelyNotJosh** [comment]
+1

**Comment by nikrozman21** [comment]
Sorry, the existing information isn't getting removed.
I believe there's no conflicting info anymore. Just like any other company that's having issues with either hardware or something else, it's staying on here until the issue is resolved.

**Comment by DCunninghamICX** [comment]
Everything seems good now. 

Thank you kindly sir.

**Comment by DefinitelyNotJosh** [comment]
> Sorry, the existing information isn't getting removed.
> I believe there's no conflicting info anymore. Just like any other company that's having issues with either hardware or something else, it's staying on here until the issue is resolved.

Having issues with hardware does not warrant a place on the SH list. They've shown an effort to rectify the issue (which they have now successfully done) meaning there's no reason whatsoever to say on here.

**Comment by DefinitelyNotJosh** [comment]
Why is this closed when they've rectified the issue @nikrozman21?

**Comment by DCunninghamICX** [comment]
> > Sorry, the existing information isn't getting removed.
> > I believe there's no conflicting info anymore. Just like any other company that's having issues with either hardware or something else, it's staying on here until the issue is resolved.
> 
> Having issues with hardware does not warrant a place on the SH list. They've shown an effort to rectify the issue (which they have now successfully done) meaning there's no reason whatsoever to say on here.

I'm not sure why its not closed but at this point its irrelevant to keep trying. Obviously we will not be removed no matter what we do or achieve.

**Comment by nikrozman21** [comment]
The thing is that you are on here for providing services while having such issues. Just like anyone else with poorly performing HW, you are listed on here.

**Pull request closed without merging**
