### PR TITLE
Add ReallyFast LLC

### PR DESCRIPTION
**Pull request by hb4uhomebrew**
https://discord.gg/znktkt2 all you need

### CODE REVIEW

**Comment by RyderAsKing** [comment]
I had a 128 GB RAM node from that hosting, i still do but yeah i have been told to backup all the stuff cuz the partnered node which i had will be removed in 5 days (As of said by a staff known as EpicLiker) 

rfh
staff

**Comment by Ethereal739** [comment]
I will need more proof on this one.

**Comment by hb4uhomebrew** [comment]
https://i.imgur.com/qTYFCud.png There discord was left, raided & the staff made it so u can talk in announcements, many are chargebacking. https://i.imgur.com/JrNirpK.png https://i.imgur.com/0TomuCL.png Ethereal trust the community, they are a scam.

**Comment by AshleyHunter01** [comment]
image
EpicLiker was staff there and he told me the owner did an exit scam

**Comment by RyderAsKing** [comment]
My lifetime vps lasted 9 days oof and i see a new message in the announcement bruh 
Screenshot (356)

**Pull request merged**
