### PR TITLE
Updated Nginx.conf

### PR DESCRIPTION
**Pull request by TonyS95**
added 404 file ^^

### CODE REVIEW

**Comment by TonyS95** [comment]
added 404 file to nginx conf*

**Comment by ygtripps** [comment]
Fucking meme.

**Comment by TonyS95** [comment]
Your a meme bripps

**Comment by DefinitelyNotJosh** [comment]
What's the point of this PR? NGINX configs aren't placed in the website's directory.

**Comment by TonyS95** [comment]
This can be closed it already got accepted.

**Pull request merged**
