### PR TITLE
Add PixelNodes

### PR DESCRIPTION
**Pull request by HeavenPE**

### CODE REVIEW

**Comment by Daxorinator** [comment]
Please update your commit to be slightly more formal.
See other hosts on SummerHoax as an example.

Please post proof of your accusations either as screenshots, chat-logs or in other forms, here on this PR.

**Comment by HeavenPE** [comment]
Screenshot_2019-10-06-15-47-30-1
Screenshot_2019-10-06-15-47-23-1
you can join their discord to see it by yourself :+1:

**Comment by RyderAsKing** [comment]
> Screenshot_2019-10-06-15-47-30-1
> Screenshot_2019-10-06-15-47-23-1
> you can join their discord to see it by yourself 👍

Well thats simply a 10 gb RAM server which was said by the owner himself.. (BTW owner is a 13 yr kid bruh who cant afford a domain)

**Comment by HeavenPE** [comment]
Screenshot_2019-10-06-15-47-39
Also they are run by former (falixnodes) staffs

**Comment by HeavenPE** [comment]
They keep purging the chat everytime on their discord, idk why but they do. if u join by any chance to verify, u will see that almost all their channels are empty

**Comment by RyderAsKing** [comment]
> Screenshot_2019-10-06-15-47-39
> Also they are run by former (falixnodes) staffs

Can you prove that PixelNodes has a stable owner and is it even a registered company, Does it have any clients who can prove it is a valid host and can i see the the specs of the "512 GB RAM Node " thorugh the command line? And if possible record a video cuz u can simply inspect element if it is a browser SSH and can photo shop it if it is a pic taken from a application like putty

**Comment by HeavenPE** [comment]
Just got banned on their discord server for making this PR!😂😂

**Comment by Daxorinator** [comment]
Motioning to merge, after the PR is tidied up a bit.

Again, please formalize what you've written in the PR, see other hosts for example.
Then we can merge this PR.

**Comment by HeavenPE** [comment]
Well sir, can u help me a little bit by editing the PR making it valid to merge cause idk what to edit to make it tidy enough lol. Please😊😊

**Comment by HeavenPE** [comment]
Screenshot_2019-10-06-17-11-35-1
Proof of me being banned because of this PR😂😂

**Comment by HeavenPE** [comment]
Screenshot_2019-10-06-17-22-31-1
results of this PR😂😂😂

**Comment by HeavenPE** [comment]
Screenshot_2019-10-06-18-07-33-1
creator accepted himself lmao😂😂

**Comment by HeavenPE** [comment]
Screenshot_2019-10-06-17-59-40-1
am i mean?? should i delete this PR??

**Comment by HeavenPE** [comment]
Screenshot_2019-10-06-18-20-58-1
oohh so now am offered to be unbanned LOL😂😂😂 good job zook

**Comment by HeavenPE** [comment]
Screenshot_2019-10-06-17-32-40-1
Tried to change the name bruhh?? Damn i made him popular on summerhoax! He was just a good student following the summerhoax guide.

**Comment by cookiesoof** [comment]
1. As you can see, there only staff in there. and it doesn't release yet.
2. You are treating me just because want "CEO".
3. It started as joke, but you take it too seriously.

**Comment by cookiesoof** [comment]
And also, i left as owner from "Easly.host"  because i know it nulled theme. Triassic say it his friend theme, but actually no

**Comment by cookiesoof** [comment]
I didn even leak anything, no leaked software.

**Comment by HeavenPE** [comment]
Learn some grammar kid😂😂😂

**Comment by HeavenPE** [comment]
i didnt say u leaked anything. i said u used nulled ptetodactyl themes.

**Comment by HeavenPE** [comment]
You left Easly.host and started another summerhoax similar to Easly💪

**Comment by cookiesoof** [comment]
I use free theme. It doesnt even leaked/nulled. 
https://github.com/TheFonix/Pterodactyl-Themes

**Comment by HeavenPE** [comment]
U guys were using nulled argon theme before this!! U CHANGE IT😂😂

**Comment by cookiesoof** [comment]
I left that stupid host just because they all dumb.

**Comment by cookiesoof** [comment]
Uh sorry, argon? uhh i doesnt use argon.

**Comment by cookiesoof** [comment]
And also, why i use argon. where did i got them. well i wont make account in any leak site

**Comment by cookiesoof** [comment]
I care my privacy and security

**Comment by cookiesoof** [comment]
Only dumb people use nulled theme

**Comment by cookiesoof** [comment]
Because they doesnt care privacy and security

**Comment by HeavenPE** [comment]
lol ethereal will understand by your grammar. also the leaked argon from blackspigot is on github so you didnt have to make any kind of 'accounts'

**Comment by cookiesoof** [comment]
I wont use leaked/nulled theme because i care people security

**Comment by cookiesoof** [comment]
Why would i use stupid theme which harm people

**Comment by HeavenPE** [comment]
I wont bother replying to you anymore😂😂!! The screenshots are enough to bring you down LOL😂

**Comment by cookiesoof** [comment]
I know you trying to take me down because i didn't give you stupid "CEO"

**Comment by HeavenPE** [comment]
whatever LOL😂This is where your crappy host deserved😂😂😂

**Comment by cookiesoof** [comment]
You didn't deserve stupid "CEO" with admin panel. You gonna ruin everything

**Comment by HeavenPE** [comment]
Enjoy summerhoax😂😂😂

**Comment by HeavenPE** [comment]
@Ethereal739 can u review this one please xD

**Pull request closed without merging**
