### PR TITLE
Added TermsGames to the Vault

### PR DESCRIPTION
**Pull request by Daxorinator**
Added TermsGames to the vault for scamming, selling dodgy windows keys, reselling nulled themes, banning people if they don't give him money, shutting down his clients machines and not allowing backups when he can't afford to keep the machines on.

Proof below:

https://cdn.discordapp.com/attachments/439504615684177940/581790657333690372/unknown.png

https://cdn.discordapp.com/attachments/439504615684177940/581790740468989972/unknown.png

https://cdn.discordapp.com/attachments/439504615684177940/581790878855856138/unknown.png

https://cdn.discordapp.com/attachments/439504615684177940/581840609405304842/unknown.png

https://cdn.discordapp.com/attachments/439504615684177940/581841084552839179/unknown.png

https://cdn.discordapp.com/attachments/439504615684177940/581842581802188819/unknown.png

https://cdn.discordapp.com/attachments/439504615684177940/581842886287556630/unknown.png

https://cdn.discordapp.com/attachments/439504615684177940/581843419433795595/unknown.png

I would have liked to add his host `veneliumhosting.com` to the SH list, however there's little wrong with the company itself as they have a valid WHMCS license and aren't doing anything else sketchy. It's just the owner himself who is an utter cock and deserves to be on this list for being a douche. 

The owner also has been a part of communities in the past and decided to branch away from them and chat shit behind the owners backs. Please note that I was not involved with TermsGames in any way, nor was I involved with Jonny when these events occurred, I'm simply submitting the PR with as much evidence as I can give, as the guys hosting company looks sketchy at best, with outrageous pricing and the owner as I have said has shown himself to be a massive cock.

### CODE REVIEW

**Comment by nikrozman21** [comment]
I don't see how he tried scamming you.

Can you please elaborate on what exactly was scammed or being attempted.
What did you buy from him etc...

**Comment by Jonnyfencing1** [comment]
> I don't see how he tried scamming you.
> 
> Can you please elaborate on what exactly was scammed or being attempted.
> What did you buy from him etc...

He was supposed to do work for me to setup Unturned on TCAdmin and then never did

**Comment by termsgames** [comment]
What on earth are you on about?

The windows keys are directly from Microsoft.

I've never sold any "nulled" theme. Please provide proof.

Furthermore, my company is in good standing and has had nothing but positive feedback and suggestions. The prices arent "outrageous", they're priced based on quality and support.

Me and Jonny have had a bit of history about a year ago, but that should of since been resolved. Jonny even bought hosting from us about a month ago.

How is this anything to do with Venelium Hosting and why hasn't Jonny made the PR?

I

**Comment by DefinitelyNotJosh** [comment]
> I've never sold any "nulled" theme. Please provide proof.

Why were you offering it at a cheaper price then?

**Comment by termsgames** [comment]
What theme? I was selling him a service for me to add an Unturnrd script to his tcadmin.

**Comment by DefinitelyNotJosh** [comment]
> What theme? I was selling him a service for me to add an Unturnrd script to his tcadmin.

https://cdn.discordapp.com/attachments/439504615684177940/581841084552839179/unknown.png

I quote "you know that cloud **theme**".

**Comment by termsgames** [comment]
How does that mean i was selling a "nulled theme"?

**Comment by DefinitelyNotJosh** [comment]
> How does that mean i was selling a "nulled theme"?

You were selling it at a cheaper price than it is usually.

**Comment by termsgames** [comment]
Please link me the theme i was supposedly selling. This proof isnt substantial and all that can be proved from this so far is that I didnt do the service he paid me to do. However, he got his money back.

**Comment by DefinitelyNotJosh** [comment]
> Please link me the theme i was supposedly selling. "Cloud" is a very broad term. This proof isnt substantial and all that can be proved from this so far is that I didnt do the service he paid me to do. However, he got his money back.

I'm afraid there's more than that. You said "you know that cloud **theme**", therefore it's quite specific.

**Comment by DefinitelyNotJosh** [comment]
Also, Jonny knew what you were talking about (as far as I can tell from that conversation) and he's saying that you were talking about a theme/template, so there is enough evidence against you.

**Comment by termsgames** [comment]
Please search up cloud theme and send me a screenshot of all the results that appear. This isnt evidence for me selling a theme.

**Comment by DefinitelyNotJosh** [comment]
> Please search up cloud theme and send me a screenshot of all the results that appear. This isnt evidence for me selling a theme.

http://prntscr.com/ntfqcj Somehow I doubt you were attempting to sell an MP3 of the main theme of Final Fantasy VII.

Jonny is saying you were trying to sell a nulled theme. And it's quite obvious you were.

**Comment by termsgames** [comment]
Theres hundred of results on themeforest for cloud themes, as well as that I could of been selling a theme I bought previously for a reduced price. The license they offer Is valid for one client.

These are also my last messages to Jonny, theres no reason why he should of decided to bring this up over a year after it happened. https://i.postimg.cc/WzCQZXsM/Screenshot-20190526-082658-Discord.jpg

It also still stands that he recieved his money back after the dispute was made. I do admit the decision of me not going through with the service he asked for from me wasnt a great idea, but it was tricky for me at those times.

**Comment by DefinitelyNotJosh** [comment]
> Theres hundred of results on themeforest for cloud themes, as well as that I could of been selling a theme I bought previously for a reduced price. The license they offer Is valid for one client.
> 
> These are also my last messages to Jonny, theres no reason why he should of decided to bring this up over a year after it happened. https://i.postimg.cc/WzCQZXsM/Screenshot-20190526-082658-Discord.jpg
> 
> It also still stands that he recieved his money back after the dispute was made. I do admit the decision of me not going through with the service he asked for from me wasnt a great idea, but it was tricky for me at those times.

You can't resell a theme without express permission from the developer. If you're able to explain exactly what you meant by "cloud theme" then we can reconsider reversing this PR.

**Comment by termsgames** [comment]
I believe it was the cloudhub theme. I wasnt using the theme so decided to sell the license. As I said, this is over a year old so it's a bit hazy. We all make a few small bad decisions, and that was one of them.

I quickly realised my actions and have been running 2 professionally ran businesses since then.

Also, if I'm not mistaken, Jonny's hosting company was one of the first listed on summerhost.

**Comment by DefinitelyNotJosh** [comment]
> I believe it was the cloudhub theme. I wasnt using the theme so decided to try and sell the license. As I said, this is over a year old so it's a bit hazy. We all make a few small bad decisions, and that was one of them.
> 
> I quickly realised my actions and have been running multiple professionally ran businesses since then.
> 
> Also, if I'm not mistaken, Jonny's hosting company was one of the first listed on summerhost.

Welp, you're not allowed to resell it.

**Comment by termsgames** [comment]
Yeha and that was a mistake trying to, but I never actually did sell the license.

**Comment by DefinitelyNotJosh** [comment]
> Yeha and that was a mistake trying to, but I never actually did sell the license.

You still had the intention to. But alright.

**Comment by termsgames** [comment]
The intention to sell a themeforest license isnt the same as actually going through and selling it.

The amount of evidence and explanation I've provided to this completely ridiculous PR clearly outweighs anything that's been said against me. I've even admitted to not going through the deal me and Jonny had, but he got his money back. End of.

Not once has Jonny even responded to anything I've said on here.

**Comment by Ethereal739** [comment]
If I read this correctly, you said you couldn't be arsed to offer a refund for a service you did not do?

**Comment by termsgames** [comment]
He received the money back as the dispute went in his favour I believe.

**Comment by DefinitelyNotJosh** [comment]
Oh, now that's completely bad.

He had to open a dispute. That's not you refunding him - you had the intention to keep the money, also known as intent to scam.

**Comment by termsgames** [comment]
At the time I "cba to refund him", which was pretty ignorant of me. However, I didnt fight the claim he opened or get involved with it so the claim went in his favour.

**Comment by DefinitelyNotJosh** [comment]
> At the time I "cba to refund him", which was pretty ignorant of me. However, I didnt fight the claim he opened or get involved with it so the claim went in his favour.

Alright, but you still should have refunded him in the first place. Otherwise the dispute wouldn't have been opened.

**Comment by termsgames** [comment]
Yeah I already said I should of, but at the time I didnt. I'm admitting to my mistake.

At the end of the day, he got his money back, he then proceeded to still buy hosting from me a year later and now for some reason doesnt respond to my messages.

This is supposed to be a PR from the person that alleged what I've supposedly done, however it isnt. It was posted by someone that has no involvement what so ever.

**Comment by jproutbusiness** [comment]
> Yeah I already said I should of, but at the time I didnt. I'm admitting to my mistake.
> 
> At the end of the day, he got his money back, he then proceeded to still buy hosting from me a year later and now for some reason doesnt respond to my messages.
> 
> This is supposed to be a PR from the person that alleged what I've supposedly done, however it isnt. It was posted by someone that has no involvement what so ever.
> 
> The only semi-factual claim is that I didnt process the refund directly, a claim had to be opened for it.

Dude you don't have to explain yourself to these fucking kids.

**Comment by termsgames** [comment]
Eh I feel it's best to be open, but it is getting increasingly annoying having to repeat what I've already said.

**Comment by jproutbusiness** [comment]
So your sites gonna be on summerhoax no fucking legit people in the industry even look at this kiddie ass website full of trolls and unvetted information. 

People are just trying to make themselves relevant when they aren't. The whole operation needs a fucking makeover and needs owners who actually know what they're doing and aren't kids.

**Comment by jproutbusiness** [comment]
Then they open a knockoff MC-Market forum lolz get fucking real.

**Comment by termsgames** [comment]
Yeah I do partly agree with that actually. This PR wasnt even opened by Jonny, instead by some completely random person. 

As well as that, they decided to add me to the website even before I had time to respond.

All the information provided in this ridiculous PR is also false apart from some of the screenshots which I've admitted to being my fault on multiple occasions.

Summerhost was an absolute disaster and it looks like that might be a recurrence. They accept PR's with little to no evidence to backup claims.

Also, why is there people going around making PR's for companies if they just dont like the owner of them. This should be a website that outlines specific hosts with substantial proof to backup any claim made, and not some website that adds specific people and hosts with little to no evidence.

**Comment by jproutbusiness** [comment]
> > At the time I "cba to refund him", which was pretty ignorant of me. However, I didnt fight the claim he opened or get involved with it so the claim went in his favour.
> 
> Alright, but you still should have refunded him in the first place. Otherwise the dispute wouldn't have been opened.

WTF does that matter you don't work for his company you don't know what policies they have and what approval times for refunds and such. How the fuck can you tell him he should have done something/refund like you run his company or something nigga stay in your lane you don't run his shit your just on the outside looking in. Shits ridicules bro!

**Comment by Ethereal739** [comment]
So, you didn't give him the service and "cba" to give him a refund until he opens a dispute?

**Comment by termsgames** [comment]
Yes and as I said, that was a mistake. He opened the dispute and won it. He got his money back.

I shouldnt of offered him the service in the first place, if I wasnt willing to go through with it.

This has all been covered in everything I've already said.

**Pull request merged**
