### PR TITLE
Removal of FragbyteHosting.co.uk

### PR DESCRIPTION
**Pull request by miecraftdan1234**
Complete change of systems, no longer use Google cloud platform for hosting.
Contact minecraftdan1234#1234 for proof.
Completely legitimate hosting now.

### CODE REVIEW

**Comment by Ethereal739** [comment]
Please post your proof here. 
Also, may I ask how are you going to accept payment from your clients? You don't seem to have a legal WHMCS license.

**Comment by miecraftdan1234** [comment]
Hi Thien,

It's easier to use discord to send it overwise I am going to have to change my email to admin@fragbytehosting.co.uk on my GitHub account. Is that ok with you?

Thanks, Dan

________________________________

**Comment by miecraftdan1234** [comment]
Hey there Tonis,

We use Hezner for our main node, and Strato for our nameservers, you can check the IP addresses by pinging each of our systems. We do not use WHMCS for collecting payments until the end of June, when we will be back up and running again. We will use PayPal to collect payments from clients.

Thanks, Dan

________________________________

**Comment by Ethereal739** [comment]
Not sure if Discord even allows you to use their service to accept payment lol. Also, it is extremely unprofessional to not even have a working website and accept payment via Discord.

**Comment by miecraftdan1234** [comment]
So, what's going on then, is this closed now or what? We don't take payments through discord, and wont be using WHMCS until the end of June. Do you need any other proof to remove fragbytehosting from the site?

Thanks, Dan

________________________________

**Comment by DamonOnYT** [comment]
nice self-signed SSL certificate

Screen Shot 2019-06-17 at 5 39 38 pm
Screen Shot 2019-06-17 at 5 39 53 pm

**Comment by miecraftdan1234** [comment]
Hi,

It uses letsencrypt for its certificate, not self signed. We tried to use self signed, but it failed, so we use let's encrypt. Also, check the domain again, you did this on the 15th June when we were doing resets and migration.

Thanks, Dan

________________________________

**Comment by DamonOnYT** [comment]
I literally took the screenshot right before I sent the image here.

**Comment by DamonOnYT** [comment]
Screen Shot 2019-06-17 at 5 53 54 pm

**Comment by miecraftdan1234** [comment]
Apologizes, it seems to be an error on our end, I will resolve when I can, it's definitely secured by letsencrypt when properly online.

Thanks, Dan

________________________________

**Pull request closed without merging**
