### PR TITLE
FalixNodes is no longer existing.

### PR DESCRIPTION
**Pull request by FalixNodes**

### CODE REVIEW

**Comment by hb4uhomebrew** [comment]
Sooo falix was a summerhoax + an exit scam, goodjob.

**Comment by Daxorinator** [comment]
Hi,

Thank you for your contribution, unfortunately no host can be removed unless evidence as to WHY they should be removed is provided.

As it is the case that FalixNode no longer exists, you can instead submit a new pull request, moving FalixNodes to the "WinterHosts" section, where we put hosts that have closed down.

This is to ensure a solid record is kept of hosts who were on the list and closed, vs hosts that got removed after proving they shouldn't be on the list. It also keeps a solid record of hosts that are still need to be on the list, active or not.

**Comment by KidsAreSalty** [comment]
> Hi,
> 
> Thank you for your contribution, unfortunately no host can be removed unless evidence as to WHY they should be removed is provided.
> 
> As it is the case that FalixNode no longer exists, you can instead submit a new pull request, moving FalixNodes to the "WinterHosts" section, where we put hosts that have closed down.
> 
> This is to ensure a solid record is kept of hosts who were on the list and closed, vs hosts that got removed after proving they shouldn't be on the list. It also keeps a solid record of hosts that are still need to be on the list, active or not.

r u a mod

**Comment by Daxorinator** [comment]
> > Hi,
> > Thank you for your contribution, unfortunately no host can be removed unless evidence as to WHY they should be removed is provided.
> > As it is the case that FalixNode no longer exists, you can instead submit a new pull request, moving FalixNodes to the "WinterHosts" section, where we put hosts that have closed down.
> > This is to ensure a solid record is kept of hosts who were on the list and closed, vs hosts that got removed after proving they shouldn't be on the list. It also keeps a solid record of hosts that are still need to be on the list, active or not.
> 
> r u a mod

r u bent

**Comment by Alontrle** [comment]
FalixNode's has on several occasions today (since announcing closure) that they are planning to re-open and already have new servers purchased.

Proof: (All taken on 9/2/2019)
https://cdn.discordapp.com/attachments/571922612230422530/618134792600551424/unknown.png
https://cdn.discordapp.com/attachments/571922612230422530/618134923236081675/unknown.png
https://cdn.discordapp.com/attachments/571922612230422530/618134852943740968/unknown.png

**Comment by Ethereal739** [comment]
Good job with your exit scam, fake closing down the host to have it removed then reopening it lol. I will not only deny this PR, but also make a section dedicated to FalixNodes on the main page and add all the new fancy evidence of your illegal conduct, including identity theft. @FalixNodes

**Pull request closed without merging**
