### PR TITLE
Daniel Dore-Meads

### PR DESCRIPTION
**Pull request by Qubopp**
Daniel Dore-Meads, the owner of the sketchy Fragbyte Hosting LTD. Lied about being registered for months until he begrudgingly used Rapid Formations. Used Strato VPS's for months and months paying 1 euro a month and as soon as his 6 month deal refused to pay any of the invoices.

*gonna add a indepth PR on fragbyte hosting with screenshots*

### CODE REVIEW

**Comment by FragbyteHostingLTD** [comment]
Hi All,

FBH MD Dan DM here. I am wanting to add my opinion on the matter regarding this PR. 

Firstly, we are still waiting for the "In depth PR on us with screenshots", which is surprising. 21 days ago this was created, seems incredibly long now and pointless to even make this request.

Next, "The owner of Sketchy FBH LTD" is a very bold statement. I am neither sketchy nor 'up to something', so please enlighten me with that.

"Lied about being registered for months until he begrudgingly used Rapid Formations." Excuse me, pardon? We started in December around the 28th and we started planning out the company. We did not have clients at the time nor had a discord. We created these, and got registered in January. I am unsure where you got the "Lied for months" part from, since I even showed you many times the companies house page and discord registration date.

When the discord was created:
image
When we got registered:
image
image

Yes, we did use Strato's VPS's for months, then left them. We paid all invoices and used their services correctly. Since we have stopped using them as our hosting platform, we can no longer login to prove the evidence necessary, as seen below.
image

If you have the so called "Evidence" with screenshots, it would be much appreciated if you add it here so I can explain the points you have given.

Just to say, not being offensive/rude or anything, but since I was called, and I quote "you've been quite a dick lately" & "cunt" in some places according to yourself, you proceed to make a PR on a company **you** worked for then decide to show us up for no apparent reason? Seriously, worry about your own life than bothering making PR's like this that aren't valid in the slightest.

**To all viewers:** Us as a company is not hiding evidence or valid proof to anyone and we can provide all the evidence you require for this PR to be closed within reason.

Please let me know if you have anything else to say.

**Thanks, Dan
Managing Director
Fragbyte Hosting LTD**

**Comment by Qubopp** [comment]
So you wouldn't mind me uploading the unpaid invoices and voice recordings of you saying you will not pay them invoices?

**Comment by Endeavor756** [comment]
I just find it really funny how you've opened this PR instead of defending yourself on the PR about your host.

I also find it really funny that you have to ask before uploading evidence as if you're giving them a chance to say no on a certain condition (blackmail?), because you certainly wouldn't be the type to just not post their evidence for a price.

If you've got something to say, just fucking say it. Post your evidence instead of having a bitch fight in the PR. This has been open for 23 days and you didn't have the balls to post anything against Fragbyte and are just making bold presumptuous statements backed by zero fact whatsoever.

And to Dan, the Strato login failed screenshot proves nothing as you could easily keyboard smash login and it wouldn't be valid, obviously.

**Comment by Qubopp** [comment]
I'm still putting all the files together/looking for them as I was locked out of the staff chat.

**Comment by FragbyteHostingLTD** [comment]
Hi All,

Firstly, apologises for the Strato evidence there, I can provide discord screen share evidence of this anyway with me logging in with old credentials and I get that error. Not really much else I can do except show chats with Strato in Facebook Messenger about my services.

Next, this line of

> I just find it really funny how you've opened this PR instead of defending yourself on the PR about your host.

Not sure what you mean by this, as I am defending the host? Christian was let off our staff management team, so I am defending FBH, not him at all.

>I was locked out of the staff chat.

Proceeds to take evidence from the network staff chat for this PR, which I find totally disrespectful, but anyway... Staff chat was deleted and we moved back to discord. 

> I'm still putting all the files together/looking for them

Dude, it has been 24 days, get a move on. Stop being lazy and show us valid evidence to support your statements.

**Comment by Qubopp** [comment]
Even if you screenshare you logging into Strato that literally makes no difference, now, if you don't mind me putting this out here, the reason I was 'let go' was because I was looking at other positions at other companies and it just so happens that the owner of this company I was looking at told Dan that I was looking at a job at his company. And even though I hadn't even applied, Dan thought it would be great to fire me. 

image
_Just a few announcements from the fuck fest of announcements_

Mr Day, the other Director is also rarely available, not sure about now but I'm pretty darn sure he won't be any more available than he was, but he is the only one with access to the company bank account (18 months included with RapidFormations). This means that when he was having some personal issues and wasn't coming online the company was slowly crawling into debt, the last I knew, it was 50 pounds. And considering Mr Day is rarely available I doubt it's been paid.

Dan, remember when you were crying on VC about the audit coming up in January? How you don't have all the financial data that's needed for then? I do.

I also remember you lying MANY times about FBH's use of GCP. You always told me that it was because a client wanted access to the control panel, which is obviously stupid, but I believed you. But guess what, when Dennis came onto the team he set the truth straight and I was pissed with you. And then you begged and begged for forgiveness.

Remember the time you yelled at me over VC for just trying to talk to me and telling me I should quit? I do, and you were DMing me on your alt and begging for forgiveness? I definitely do, I really regret unblocking you that day. 

When I first met you, you were a pretty chill dude, but now, you're a caniving, lying control freak of a prick. 

I honestly regret asking you for a 'job'.
You made promises 'I will pay you soon' and I kept watching the all time stat on WHMCS go up and up and up. But guess what, that paypal balance of mine aint going up.

**Comment by Qubopp** [comment]
Oh, and nice blatant name calling in announcements about your client's servers.

**Comment by Qubopp** [comment]
image
Thought I would mention the fuck fest that was the IcedHost migration, makes me laugh to this day. 300 something pound for '300 something clients' and about 30 or 40 actually migrated. Even included a very broken panel.

**Comment by Endeavor756** [comment]
I should have formatted my comment better. I'm on phone so it's a bit difficult.


TO QUBOPP:
I just find it really funny how you've opened this PR instead of defending yourself on the PR about your host.

I also find it really funny that you have to ask before uploading evidence as if you're giving them a chance to say no on a certain condition (blackmail?), because you certainly wouldn't be the type to just not post their evidence for a price.

If you've got something to say, just fucking say it. Post your evidence instead of having a bitch fight in the PR. This has been open for 23 days and you didn't have the balls to post anything against Fragbyte and are just making bold presumptuous statements backed by zero fact whatsoever.

===========

TO DAN:
And to Dan, the Strato login failed screenshot proves nothing as you could easily keyboard smash login and it wouldn't be valid, obviously.

**Comment by Qubopp** [comment]
It's closed, end of.

**Comment by Endeavor756** [comment]
Well, 'scuse me. It might be closed which prevents it from being merged. What it isn't is locked, which doesn't stop me or anything for writing a reply. You've submitted something on a thread publicly and online for people to see, you should expect people will still talk about it even after it's closed. There is nothing that says I can't reply to an old issue or PR to clear a misunderstanding.

**Comment by FragbyteHostingLTD** [comment]
Hi Endeavor,

Thanks for explaining that for me and apologies if I came across as rude.
I will close off here saying it's dealt with, but add anything else as you will.

Thanks, Dan

**Pull request closed without merging**
