### PR TITLE
Added MyServerPlanet

### PR DESCRIPTION
**Pull request by eatingenderman89**

### CODE REVIEW

**Comment by eatingenderman89** [comment]
ahahha i do not appreciate you

**Comment by KidsAreSalty** [comment]
Kermit sewer side

**Comment by eatingenderman89** [comment]
I like how you say
"His new host if it’s still up is Enderify
LOL HE JUST OPENED A NEW ONE"
when i dont even own that host,

**Comment by Ethereal739** [comment]
Enjoy your ban from the repo.

**Comment by eatingenderman89** [comment]
thanks

**Pull request closed without merging**
