### PR TITLE
Add Marzmediahosting

### PR DESCRIPTION
**Pull request by hb4uhomebrew**
I did this PR for "TheDeathStreamer" as he did not know how to do it.
Proof:
=======
https://images-ext-1.discordapp.net/external/bLRm38VaxyDWYkGfJquzUbg5pICMY6ZvCWmDgk5M7Ts/https/i.imgur.com/LWeyOeK.png?width=578&height=670
https://i.imgur.com/22adMPI.png
https://i.imgur.com/g49gscd.png

### CODE REVIEW

**Comment by hb4uhomebrew** [comment]
Note I'm not affiliated with either side, I'm pull requesting for someone who doesn't know how.

**Comment by TheDeathStreamer** [comment]
Owner offered discord hosting, used me for whmcs setup as he is too lazy, I never got anything in return, using broken old computers to host, blamed me for his wifi issues, tried making me pay for the hosting after giving it to me for free, gave me access to the computer where it was hosted and when I tried getting my files he then kicked me off, I told him im going to switch host and he then deleted my files and started calling me an ass and told me to never contact him.


To sum up the photos

**Comment by TheDeathStreamer** [comment]
domain: marzmediahosting.com

**Comment by DamonOnYT** [comment]
They are also kinda impersonating a videography company run by a well known YouTuber https://www.marz.media/

**Comment by Qubopp** [comment]
Yeah I've given Alex a heads up, watch/watched him when I was younger lmao

**Comment by TheDeathStreamer** [comment]
Yeah, I thought I new something was off about the name, now people are just gonna get confused and thing the owner is someone else or think its a "famous" website xdddd

**Comment by falceso** [comment]
They may have closed already. 😅 I'll wait a couple of days, before we file this into Frozen Winter Hoaxes.

**Pull request merged**
