### PR TITLE
Some fixing here

### PR DESCRIPTION
**Pull request by itsgatto**

### CODE REVIEW

**Comment by itsgatto** [comment]
added securesrv to certified summerhosts

**Comment by nikrozman21** [comment]
I'd say lets keep it as it was originally made. Perhaps make a button that toggles the shit mode to good mode and make it change that Contabo -> SecureSRV part out.

**Comment by ygtripps** [comment]
I mean all the code does is check the websites version, then if it matches it will allow the script to continue removing it from the swarm, if it isn't then it gets dropped. I did this in my plugin but without the concept of a swarm, just simply a pastebin link that said false. Once it got leaked I changed the text to a non-boolean form (asdfaasdfasdf for example), and it would send a message saying an update is available. Same thing he did but mine is just in a simpler form without the logging.

Breakdown of his code:
584045a7-1cf7-4cc8-a0cb-a3f728b09e98

**Comment by itsgatto** [comment]
I'm just going to clarify this.

I'm a director of SecureSRV and part owner of it along with HeavyNode. This PR was just a meme that I was playing on Ethereal when I was bored. c:

**Pull request closed without merging**
