### PR TITLE
Request for Removal: Webrex Hosting

### PR DESCRIPTION
**Pull request by falceso**
**Requested by:** @BigDaddyBanana
**Originally added by:** @Cyclops0666
**Request Received thru:** Discord Direct Messages
**Reason for Appeal:** 

> My hosting. Sure. It isn’t perfect and it’s still in its developmental phases. But it isn’t a summer host. Just needs work is all. I’ve seen much worse. We are a pretty organized group of people. I like to keep everything in order. As for me. I am not a pedophile. The reason that kid said I was it literally because I wouldn’t pay him because he didn’t do the work he was asked to do and still wanted paid. In fact he was a insane amount of money for minimal work done.

**Response to Question:** 
>**Question**: *claiming to be registed when you are not is illegal and the site was a replica*
>**Response:** I never said I was registered...? Because I’m not?
enter image description here

**Additional Notes:** Internal discussion was initialized on a verdict, but communication dropped off on the status. For transparency sake, this Pull Request has been released public. Webrex Hosting initially opened 2015, went bankrupt in 2017, and has now re-opened under new managed as of 2018.
**Personal Verdict** Approve Removal, company appears organized thru the view of their Discord. Reasonable transparency and an open connection with clients. Host is until now **Work in Progress**, but it appears to function successfully with a valid WHMCS license, nicely designed Pterodactyl Setup, and an offline status page  _(alternative setup in discord regards status has been created.)_. 

**_Please chill out on the drama, unless you believe it is supplementary in the decision making of Pull Request. The requester has already ensured enough stress from the "false information" and being listed in SummerHoax._**

### CODE REVIEW

**Comment by DefinitelyNotJosh** [comment]
Dad seems like a nice guy, I'd say give him a chance as Webrex has only been running for what... a week or so? I'd close this for now and then open it again if there's a suggestion of Webrex being a SummerHoax™ in the near future.

**Comment by ygtripps** [comment]
Well the company is not registered, therefore it is staying on the list.

**Comment by DefinitelyNotJosh** [comment]
Lmao, what the heck are you thinking Tripps? There's absolutely nothing wrong with owning an unregistered company unless you're claiming you do when it's obvious you don't.

**Comment by BigDaddyBanana** [comment]
> Dad seems like a nice guy, I'd say give him a chance as Webrex has only been running for what... a week or so? I'd close this for now and then open it again if there's a suggestion of Webrex being a SummerHoax™ in the near future.

Thanks you for the kind words.

**Comment by Nobody196** [comment]
@DefinitelyNotJosh yes there is? You can't operate under a name that isn't yours if not registered afaik

**Comment by DefinitelyNotJosh** [comment]
If there's already another company with the name "Webrex" then I'd highly recommending rethinking your brand, otherwise it should be fine.

**Comment by BigDaddyBanana** [comment]
Either way, just because I’m not registered doesn’t mean I’m a summer host?

**Comment by DefinitelyNotJosh** [comment]
Precisely, unfortunately a popular impression in this industry is that if you're not registered, you're untrustworthy - that's not true by any means of course, but it's many people's mentality.

**Comment by ygtripps** [comment]
"There is nothing wrong with 'owning' an 'unregistered' 'company'", please just stop because obviously you don't know anything in regards to running a business in the US or the UK. By law they are required to have a business registered unless you are doing it under your personal name (US).

**Comment by DefinitelyNotJosh** [comment]
Ever heard of a sole trader, Tripps?

**Comment by BigDaddyBanana** [comment]
I’m going to request that we stop the drama. This is no longer contributing to the topic at hand.

“Please chill out on the drama, unless you believe it is supplementary in the decision making of Pull Request. The requester has already ensured enough stress from the "false information" and being listed in SummerHoax.”

**Comment by Nobody196** [comment]
> I’m going to request that we stop the drama. This is no longer contributing to the topic at hand.
> 
> “Please chill out on the drama, unless you believe it is supplementary in the decision making of Pull Request. The requester has already ensured enough stress from the "false information" and being listed in SummerHoax.”

Next time stop it by shutting down someone clearly misinformed from posting :)

**Comment by lazarsn** [comment]
Hmmm

**Comment by falceso** [comment]
It has been 17 hours without any major objects from an established authority. At this time, I am merging this Pull Request. This serves as notice that a removal request was filled and may affect the decision making of returning Webrex Hosting back on the SummerHoax list.

**Comment by Cyclops0666** [comment]
I'd like to reopen this PR due to the fact that everyone forgot that they DM advertised on a server. Any hosting company that does this should automatically be added to the summerhoax list.

**Comment by DefinitelyNotJosh** [comment]
> I'd like to reopen this PR due to the fact that everyone forgot that they DM advertised on a server. Any hosting company that does this should automatically be added to the summerhoax list.

Proof?

**Comment by BigDaddyBanana** [comment]
> I'd like to reopen this PR due to the fact that everyone forgot that they DM advertised on a server. Any hosting company that does this should automatically be added to the summerhoax list.

You literally already opened one, and again he gave you ample time. And plus, that was what? Months ago? Businesses make mistakes. Jesus.

**Pull request merged**
