### PR TITLE
Add PlatinumNode

### PR DESCRIPTION
**Pull request by hb4uhomebrew**
https://media.discordapp.net/attachments/571922612230422530/617007699003179018/unknown.png?width=378&height=670 - iBan proof
https://i.imgur.com/f7J8YDL.png - Sells via discord / is a free host
https://i.imgur.com/bHxOx9M.png - "CEO" is an 11 year old.

### CODE REVIEW

**Comment by hb4uhomebrew** [comment]
Also, an ItzAwesome moment... they are promoting illegal piracy & leaking https://i.imgur.com/gktKBpB.png

**Comment by KidsAreSalty** [comment]
Proof of selling way way way way more resources than they have

**Comment by mayed505** [comment]
PlatinumNode huh, reminds me of my old brand lmao.

**Comment by fantratic** [comment]
I've also experienced PlatinumNode, they've told me I would get a free server along with my purchase, I didn't get it, so I asked for a refund and they didn't provide any. I then chargedback and won it, and yea.

**Comment by falceso** [comment]
Hello,

This PR appears to be ready for addition, however as a growing effort to improving the quality of our listings. We ask you attach your evidence & re-list the reasons for being flagged as a SummerHoax.

You may find our new system over at [Revenact](https://revenact.io/forums/discussion.65/).

Sincerely,
SummerHoax Team

**Pull request closed without merging**
