### PR TITLE
Added rainhosting

### PR DESCRIPTION
**Pull request by jesgeerts**

### CODE REVIEW

**Comment by Daxorinator** [comment]
Why...?

**Comment by Daxorinator** [comment]
@jesgeerts just drop a screenshot or something and this'll be pulled fairly quick

**Comment by Daxorinator** [comment]
rainhosting.nl has a valid WHMCS license so we're definitely going to need to see proof of some description

**Comment by KidsAreSalty** [comment]
> rainhosting.nl has a valid WHMCS license so we're definitely going to need to see proof of some description

According to his PR, the reason is: They have used an illegal version of WHMCS and people are being scammed there. Domain has been seized by the hoster

However, there isn't any proof to go along with these claims

**Comment by Ethereal739** [comment]
Please add some proof.

**Comment by JW-Joey** [comment]
Jesus, No need to track the guy down. I just wanna add that i personally dealt with the owner. (Absolute Prick) Their WHMCS used to be nulled with the owner saying that they were testing the software out, Scamming part idk about. But their domain is actually seized lmao meaning he indeed did something that people didnt like, lets just wait for jesse to upload his proof, and not have the same 3 responses asking for proof 🤔

**Comment by KidsAreSalty** [comment]
Screenshot_7

**Comment by KidsAreSalty** [comment]
> Jesus, No need to track the guy down. I just wanna add that i personally dealt with the owner. (Absolute Prick) Their WHMCS used to be nulled with the owner saying that they were testing the software out, Scamming part idk about. But their domain is actually seized lmao meaning he indeed did something that people didnt like, lets just wait for jesse to upload his proof, and not have the same 3 responses asking for proof 🤔

http://www.script-o-rama.com/movie_scripts/a1/bee-movie-script-transcript-seinfeld.html

**Comment by KidsAreSalty** [comment]
> Jesus, No need to track the guy down. I just wanna add that i personally dealt with the owner. (Absolute Prick) Their WHMCS used to be nulled with the owner saying that they were testing the software out, Scamming part idk about. But their domain is actually seized lmao meaning he indeed did something that people didnt like, lets just wait for jesse to upload his proof, and not have the same 3 responses asking for proof 🤔

Screenshot_7

**Comment by JW-Joey** [comment]
We GeT iT, you can google. Still no need to bring that up on github since its literally not related to anything in here at all. Lmao

**Comment by KidsAreSalty** [comment]
> We GeT iT, you can google. Still no need to bring that up on github since its literally not related to anything in here at all. Lmao

tHeRe iS vAliD eViDiDeNcE oN tHaT iMaGe

**Comment by jesgeerts** [comment]
> @jesgeerts just drop a screenshot or something and this'll be pulled fairly quick

I've dealt with the owner several times with his activities and his main hoster took his site several times down due to an illegal installation.
Illegal installation: https://i.imgur.com/iWvt0tZ.png

The proof of scamming. Well, I'm unable to find it because of the owner keeps deleting and banning people when you're talking about.

**Comment by KidsAreSalty** [comment]
> > @jesgeerts just drop a screenshot or something and this'll be pulled fairly quick
> 
> I've dealt with the owner several times with his activities and his main hoster took his site several times down due to an illegal installation.
> Illegal installation: https://i.imgur.com/iWvt0tZ.png
> 
> The proof of scamming. Well, I'm unable to find it because of the owner keeps deleting and banning people when you're talking about.

whats the discord

**Comment by jesgeerts** [comment]
> > > @jesgeerts just drop a screenshot or something and this'll be pulled fairly quick
> > 
> > 
> > I've dealt with the owner several times with his activities and his main hoster took his site several times down due to an illegal installation.
> > Illegal installation: https://i.imgur.com/iWvt0tZ.png
> > The proof of scamming. Well, I'm unable to find it because of the owner keeps deleting and banning people when you're talking about.
> 
> whats the discord

That's easy to ask when you're banned from that discord

**Comment by Ethereal739** [comment]
Because the website is completely broken down and the accusations about, I am merging this.

**Pull request merged**
