### PR TITLE
Added MyServerPlanet

### PR DESCRIPTION
**Pull request by eatingenderman89**

### CODE REVIEW

**Comment by eatingenderman89** [comment]
hehe

**Comment by eatingenderman89** [comment]
right

**Comment by eatingenderman89** [comment]
congrats

**Comment by eatingenderman89** [comment]
you just failed

**Comment by eatingenderman89** [comment]
to

**Comment by Patrickgae** [comment]
Add me on dis my dude. I sent you a friend request.

**Comment by eatingenderman89** [comment]
ban

**Comment by eatingenderman89** [comment]
me

**Comment by eatingenderman89** [comment]
and ok

**Comment by KidsAreSalty** [comment]
> and ok

You do realize you clicked an ip logger a while back right? As a friendly reminder I would suggest changing that soon.

**Comment by eatingenderman89** [comment]
thats illegal haha also i got Hotspot Shield connected nub

**Comment by Ethereal739** [comment]
Freaking clown lol

**Comment by Apexful** [comment]
> thats illegal haha also i got Hotspot Shield connected nub

Who the fuck uses hotspot shield

**Comment by lazarsn** [comment]
:joy:

**Comment by DefinitelyNotJosh** [comment]
MyServerPlanet is a great business, and most certainly not a SummerHoax. I'm good friends with the owner and he puts hard work into the business.

**Pull request closed without merging**
