### PR TITLE
Add PhantomHost

### PR DESCRIPTION
**Pull request by HeavenPE**

### CODE REVIEW

**Comment by HeavenPE** [comment]
Screenshot_2019-12-02-00-52-34-1
As you can see above when i ping the ip address(192.3.15.12) of the node with a host checker, the organisation turns out to be (VPS ACE)(Accurate organisations)! Then i search VPS ACE on google, i get only (VPSACE.COM) and when i click that, it redirects me to https://ssdvps.com/vps-hosting/ whose prices are 👎 for someone who makes a free hosting! Its literaly 2GB ram for $15

**Comment by HeavenPE** [comment]
Screenshot_2019-12-02-01-06-03-1
Screenshot_2019-12-02-01-06-08-1
Look thats the 2nd owner and he doesnt even know the node specs😾😾

**Comment by HeavenPE** [comment]
Screenshot_2019-12-02-07-35-24
Screenshot_2019-12-02-07-35-36
And he totally ignores me after that😠😠

**Comment by HeavenPE** [comment]
Screenshot_2019-12-02-07-35-24-1
Screenshot_2019-12-02-07-35-36-1
And he totally ignores me after that😠😠 because he knows the specs he told me are fake lmao

**Comment by HeavenPE** [comment]
Screenshot_2019-12-02-07-58-53-1
Okk lets admit the host check results are false but VirMach doesnt even have a 16VCore/32GB Ram/**5.20GHZ** Plan! He is obviously lying above the specs

**Comment by tommytran732** [comment]
Heyo,

Just letting you know, I no longer accept PRs for reporting summerhoax on this repository. I am currently in the process of moving all the proofs to Revenact and the GitHub repository will be used solely for code fixes.

I would appreciate it if you can move the proof and discussion to https://revenact.io/groups/summerhoax-club-tm.22/discussions.

Regards,
Thien

**Pull request closed without merging**
