### PR TITLE
Added SparkedHost

### PR DESCRIPTION
**Pull request by Daxorinator**
Add SparkedHost for being fucking retarded.

### CODE REVIEW

**Comment by TonyMaster21** [comment]
Nah. This is totally out of context.

Gatto requested a letter of resignation, we do not send these.

Also, those payment amounts have since changed and are no longer valid.

Please get your facts straight before making accusations. Thanks!

**Comment by BigDaddyBanana** [comment]
I’m sorry what?

**Comment by DefinitelyNotJosh** [comment]
This can be closed.

**Comment by Daxorinator** [comment]
You have literally no idea why this was opened Josh.

Gatto asked for this PR to be opened so he can modify it or close it as he wishes. I'm simply requester, Gatto has all of the evidence related to this PR if you'd like to discuss it with him.

Till then, get a hold of your superiority complex.

**Comment by DefinitelyNotJosh** [comment]
Why the heck would you add pretty much the biggest GSP out there to the SummerHoax list simply because of one stupid thing the owner said?

**Comment by Daxorinator** [comment]
Ask Gatto, not me, as I said.

I respectfully ask that you not comment again until your informed.

**Comment by DefinitelyNotJosh** [comment]
I don't think you get it Dax. But as you please...

**Comment by TonyMaster21** [comment]
> Ask Gatto, not me, as I said.
> 
> I respectfully ask that you not comment again until your informed.

If Gatto requested it, why are you creating the PR?

Gatto has a GitHub and can "contribute" himself.

**Comment by DefinitelyNotJosh** [comment]
> > Ask Gatto, not me, as I said.
> > I respectfully ask that you not comment again until your informed.
> 
> If Gatto requested it, why are you creating the PR?
> 
> Gatto has a GitHub and can "contribute" himself.

I agree. This PR is irrelevant anyway unless SparkedHost as an entity has illegitimate business practices, which they most certainly do not.

**Comment by gabesystems** [comment]
I have used SparkedHost in the past, from what I have seen they use perfectly normal and legitimate business procedures. From what I have seen, they are a registered business, have friendly and active staff,  and don't do any scamming or shady activity. So personally I believe this pull request is taken out-of-context and overall unnecessary. There is no reason why an average consumer should avoid SparkedHost because you think they are "fucking retarded".

**Comment by Ethereal739** [comment]
This is irrelevant. If gatto wants to make the PR, you should let him do it himself.

**Pull request closed without merging**
