### PR TITLE
Revert "Request for Removal: Webrex Hosting"

### PR DESCRIPTION
**Pull request by Cyclops0666**
Reverts summerhoax/summerhoax.github.io#32

I'd like to revert this merge due to the fact that everyone forgot that they DM advertised on a server. Any hosting company that does this should automatically be added to the summerhoax list.

### CODE REVIEW

**Comment by BigDaddyBanana** [comment]
Okay for one. Why are you just now getting to this? Falc already said that he gave you ample time to respond and you ignored the request. Don’t say you did not see it earlier because you did. Two, the only reason your doing this is because you enjoy it. You along with a few other users attack me (dm me on discord for proof) on a daily basis when I literally don’t say a single word to you. I’ll be like “hey” and then they’ll just start grilling me about stupid shit. On top of that. That was when Webrex first opened, the business that was mentioned within the message you are referring to decided to raid my discord on a multitude of occasions, so excuse me for making a very angry decision. So please stop doing a few things:

Talking shit about things you have no idea about
Get rid of the cocky attitude
Stop targeting me (again I have images)
And leave me alone. I’m over it.

**Comment by BigDaddyBanana** [comment]
Actually, let me take this a but further and say that every time this user speaks to me it’s trash. Look, your not being cool, your not being funny. You’re just bashing some guy for absolutely no reason. Your being absolutely bias, and jt should quite distasteful. Take PloxHost, Soarked Host, all these other large hosting providers. You think they didn’t make mistakes? Did those mistakes get them on some watch list? So why should I? It’s absolutely no difference and the fact that it’s so minor. You need to grow up. Stop acting like a 5 year old, your really getting on my nerves. And please stop lying? It’s going to come out sooner or later.

**Comment by james121op** [comment]
this guy wants to be on the summersalt list

**Comment by Cyclops0666** [comment]
Responding for comment #1: I'm getting to this so late because I forgot about the DM advertising. Now, i do enjoy reporting summerhosts, because the community should be aware about them and should avoid them. Now, you said i was bashing you out for absolutely no reason? Bashing means severe criticism, and I'm pretty sure i'm not severely criticizing you. And even if you feel like i am, it's not the only reason.  Now, about the attacking. How exactly did i attack you? Please message me proof of this via dms, or here if you want. The only possible way i can think of is you thinking that saying in a general channel "I still have a dm of him mass dm'ing a server that I was in" and "He lied 20 seconds ago so that might not be the only time he lied". I cannot possibly see how this counts as attacking you. Also on a daily basis? Please get your facts straight. If you show proof of me attacking you for at least 7 days in a row, I'll close this. You've never said "Hey" to me. "Grilling" you "about stupid shit"? really? "Stupid shit", that's what you call it? I wouldn't say generally disliking you for dm advertising is Stupid, but sure, whatever. Now, it doesn't matter whether it happened when the business first opened. Well, at least i don't think it matters. The fact that you did it, for me is automatically categorizing Webrex as a summerhost. Now, you say i'm "talking shit about things" I "have no idea about"? I'm pretty sure i have a clear idea of your actions. If i don't know something be sure to dm me. Also, "cocky attitude"? Really? I'm not going to even respond to this. "Stop targeting me (I have images)" What are you on about? I have never targeted you. I've never targeted you. And in my opinion you started it because you said "I didn't mass dm any server but my own" (by the way, you should stop dm'ing your members so much. - Just my opinion.)

Responding to comment #2
Yes, every time I speak to you it's trash, well not exactly, some are facts (Like you mass dm'ing a server) and some are opinions that i would not call trash. And i'm not trying to be cool nor funny. I mentioned "bashing some guy for absolutely no reason" above. I'm not being absolutely bias because as i see it, i treat you fair. Yes some of those hosts you listed made mistakes, but i don't think any of them **mass dm'ed users on a discord advertising their hosts**. Mass dm'ing users in a server - I don't consider a minor mistake. I consider it an immense mistake. I need to grow up? Take a look in the mirror. And please explain how i am lying. **PLEASE**. I've literally looked over everything i sent to you today, and i can't see anything I'm lying about. Or maybe you forgot again, the fact that when i mentioned you mass dm'ed people, you denied it, and then stated "Yeah I'll take that L". Anything else i missed?

**Comment by BigDaddyBanana** [comment]
I have seen this and I will respond to it in the morning. Goodnight :)

**Comment by BigDaddyBanana** [comment]
I’m not even going to respond to that message because it’s essentially irrelevant, sarcastic, narcissistic, and so on. Moving on. I think I have proved my point here.

**Comment by Cyclops0666** [comment]
How is it irrelevant? How is it sarcastic? How is it narcissistic? You didn't prove anything lol. You're just avoiding my questions lmao

**Comment by BigDaddyBanana** [comment]
Literally the only point here you have is that I DM advertised ONE TIME. Businesses make mistakes, bad judgement calls. Does that get them on some watch list? No lmao. If it did this world would be absolutely fucked in the business perspective.

**Comment by Cyclops0666** [comment]
I asked you multiple questions. Be sure to answer them. And most importantly, how did I lie? You never gave any evidence of that whatsoever.

**Comment by KidsAreSalty** [comment]
> Literally the only point here you have is that I DM advertised ONE TIME. Businesses make mistakes, bad judgement calls. Does that get them on some watch list? No lmao. If it did this world would be absolutely fucked in the business perspective.

Twice* when you include me let alone all our clients.

**Comment by BigDaddyBanana** [comment]
> > Literally the only point here you have is that I DM advertised ONE TIME. Businesses make mistakes, bad judgement calls. Does that get them on some watch list? No lmao. If it did this world would be absolutely fucked in the business perspective.
> 
> Twice* when you include me let alone all our clients.

You knew saying this, mind backing it up because I have no reconcile of speaking to any of your clients. Also as your management keeps reiterating, I am banned from your server and your hosting services.

On top of this, I literally said I did it once. You obviously don’t know what the word “once” means in that context.

**Comment by KidsAreSalty** [comment]
> > > Literally the only point here you have is that I DM advertised ONE TIME. Businesses make mistakes, bad judgement calls. Does that get them on some watch list? No lmao. If it did this world would be absolutely fucked in the business perspective.
> > 
> > 
> > Twice* when you include me let alone all our clients.
> 
> You knew saying this, mind backing it up because I have no reconcile of speaking to any of your clients. Also as your management keeps reiterating, I am banned from your server and your hosting services.
> 
> On top of this, I literally said I did it once. You obviously don’t know what the word “once” means in that context.

You sent the same invite link to at least one of our clients. Literally the same minute, if not second, I got alerted you sent the same invite link to me. You obviously don't know what the word "twice" means.

**Comment by BigDaddyBanana** [comment]
> > > > Literally the only point here you have is that I DM advertised ONE TIME. Businesses make mistakes, bad judgement calls. Does that get them on some watch list? No lmao. If it did this world would be absolutely fucked in the business perspective.
> > > 
> > > 
> > > Twice* when you include me let alone all our clients.
> > 
> > 
> > You knew saying this, mind backing it up because I have no reconcile of speaking to any of your clients. Also as your management keeps reiterating, I am banned from your server and your hosting services.
> > On top of this, I literally said I did it once. You obviously don’t know what the word “once” means in that context.
> 
> You sent the same invite link to at least one of our clients. Literally the same minute, if not second, I got alerted you sent the same invite link to me. You obviously don't know what the word "twice" means.

Well, as I’ve asked you on numerous occasions to oeobide image proof of this and you have not. It’s been quite redundant to keep reply as Mr. Cyslops has already stated he is likely just going to close this.

**Comment by KidsAreSalty** [comment]
> > > > > Literally the only point here you have is that I DM advertised ONE TIME. Businesses make mistakes, bad judgement calls. Does that get them on some watch list? No lmao. If it did this world would be absolutely fucked in the business perspective.
> > > > 
> > > > 
> > > > Twice* when you include me let alone all our clients.
> > > 
> > > 
> > > You knew saying this, mind backing it up because I have no reconcile of speaking to any of your clients. Also as your management keeps reiterating, I am banned from your server and your hosting services.
> > > On top of this, I literally said I did it once. You obviously don’t know what the word “once” means in that context.
> > 
> > 
> > You sent the same invite link to at least one of our clients. Literally the same minute, if not second, I got alerted you sent the same invite link to me. You obviously don't know what the word "twice" means.
> 
> Well, as I’ve asked you on numerous occasions to oeobide image proof of this and you have not. It’s been quite redundant to keep reply as Mr. Cyslops has already stated he is likely just going to close this.

Mind telling me what account you were using? Only ask this because you've made at least 5 accounts since then to try and hide. You wouldn't have to hide if you didn't do anything wrong. Think about that.

**Comment by BigDaddyBanana** [comment]
> > > > > > Literally the only point here you have is that I DM advertised ONE TIME. Businesses make mistakes, bad judgement calls. Does that get them on some watch list? No lmao. If it did this world would be absolutely fucked in the business perspective.
> > > > > 
> > > > > 
> > > > > Twice* when you include me let alone all our clients.
> > > > 
> > > > 
> > > > You knew saying this, mind backing it up because I have no reconcile of speaking to any of your clients. Also as your management keeps reiterating, I am banned from your server and your hosting services.
> > > > On top of this, I literally said I did it once. You obviously don’t know what the word “once” means in that context.
> > > 
> > > 
> > > You sent the same invite link to at least one of our clients. Literally the same minute, if not second, I got alerted you sent the same invite link to me. You obviously don't know what the word "twice" means.
> > 
> > 
> > Well, as I’ve asked you on numerous occasions to oeobide image proof of this and you have not. It’s been quite redundant to keep reply as Mr. Cyslops has already stated he is likely just going to close this.
> 
> Mind telling me what account you were using? Only ask this because you've made at least 5 accounts since then to try and hide. You wouldn't have to hide if you didn't do anything wrong. Think about that.

In my entire what? 4 years on discord, I’ve has two accounts, the other one was removed because of some violation. Cyclops probably reported me when I did it, :P. Either way it’s quite pointless to keep posting on this. Why don’t we do something constructive?

**Comment by KidsAreSalty** [comment]
You’ve had more than 2 accounts I can think of off the top of my head... Alex P, Max P, something S, Banana-man, let alone all the times you’ve changed your name. You know there’s a reason you’re banned off MCM, Ptero, Discord and plenty of other platforms.

**Comment by BigDaddyBanana** [comment]
> You’ve had more than 2 accounts I can think of off the top of my head... Alex P, Max P, something S, Banana-man, let alone all the times you’ve changed your name. You know there’s a reason you’re banned off MCM, Ptero, Discord and plenty of other platforms.

I’m not banned off Pterodactyl, and this we’re just name changes, I’ve only had two accounts, and AGAIN please provide proof or stop trashing on me with personal bashing’s. Thank you.

**Comment by KidsAreSalty** [comment]
I mean the fact that your GitHub name is still the banana name is a bit of proof right there.

**Comment by BigDaddyBanana** [comment]
> I mean the fact that your GitHub name is still the banana name is a bit of proof right there.

I never denied that I had the name? I’m just stating that I only had two accounts. Your literally just making stuff up at this point. Stop.

**Comment by KidsAreSalty** [comment]
You said you wanted evidence? Here ya go :D now lets get this boy back on the summerhoax list.

His team discussing how they forgot to change the tos from a website they stole among other things: https://youtu.be/2zgUzd5p69s

Your team lying about you being fired after all the drama when you got exposed for being a pedo: https://youtu.be/OCiNYFk2TNw

More evidence from the last video and this one shows your other account (from the video above) being banned by discord lmfao: https://youtu.be/OCiNYFk2TNw

Check the discord for the images cause I’m doing this all on my phone and don’t wanna upload them to imgur or whatever right now.

**Comment by BigDaddyBanana** [comment]
> You said you wanted evidence? Here ya go :D now lets get this boy back on the summerhoax list.
> 
> His team discussing how they forgot to change the tos from a website they stole among other things: https://youtu.be/2zgUzd5p69s
> 
> Your team lying about you being fired after all the drama when you got exposed for being a pedo: https://youtu.be/OCiNYFk2TNw
> 
> More evidence from the last video and this one shows your other account (from the video above) being banned by discord lmfao: https://youtu.be/OCiNYFk2TNw
> 
> Check the discord for the images cause I’m doing this all on my phone and don’t wanna upload them to imgur or whatever right now.

The images he provided was from another “company” that was stolen by another user and “given to me”. I left after I found out why was going on. This is completely irrelevant.....I’m going to stop responding because this is pointless. Goodnight.

**Comment by falceso** [comment]
It appears, no certain resolution has been made yet. I will be closing this issue in a few hours due to lack of activity and no solid consensus yet.

**Comment by KidsAreSalty** [comment]
> > You said you wanted evidence? Here ya go :D now lets get this boy back on the summerhoax list.
> > His team discussing how they forgot to change the tos from a website they stole among other things: https://youtu.be/2zgUzd5p69s
> > Your team lying about you being fired after all the drama when you got exposed for being a pedo: https://youtu.be/OCiNYFk2TNw
> > More evidence from the last video and this one shows your other account (from the video above) being banned by discord lmfao: https://youtu.be/OCiNYFk2TNw
> > Check the discord for the images cause I’m doing this all on my phone and don’t wanna upload them to imgur or whatever right now.
> 
> The images he provided was from another “company” that was stolen by another user and “given to me”. I left after I found out why was going on. This is completely irrelevant.....I’m going to stop responding because this is pointless. Goodnight.

If you watch the videos, it shows you clearly knowing the website files were stolen as you and your team were seen talking about how the website copy was missing files and to go back and take them. For example the terms of service. I’d also like to point out that they use servers illegally obtained from google cloud. I do not have any proof that they are illegally obtained, but he knows very much that his provider seems a little suspicious. They’re also had major downtime lately at the same time other providers using illegally obtained good cloud servers had downtime. It may be a coincidence but it seems googles cracking down on these providers. All I ask is that before you make a final say, please make sure to watch the conversations going on in the videos and pay close attention to who he’s talking to.

**Comment by KidsAreSalty** [comment]
Sorry for the spelling errors, I’m on my phone and it’s hard to see what I’m typing after it gets certain length

**Comment by Endeavor756** [comment]
unknown
'nuff said.

**Comment by KidsAreSalty** [comment]
As soon as Harry refuses to give theme Banana changes his pr for Harry’s host to a negative statement.

**Comment by Ethereal739** [comment]
Okay so he does not know anything about his system. I think we tried to give him a chance but he still hasn't learnt anything and is keeping pretty much the same attitude.

**Pull request merged**
